// Copyright 2026 nickvasilescu. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package types

import "encoding/json"

type ActionResponse struct {
	Success bool `json:"success"`
}

type AutoStopGetResponse struct {
	AutoStopMinutes int  `json:"auto_stop_minutes"`
	Configurable    bool `json:"configurable"`
}

type AutoStopUpdateResponse struct {
	AutoStopMinutes  int    `json:"auto_stop_minutes"`
	AutoSuspendAfter string `json:"auto_suspend_after"`
}

type BashRequest struct {
	Command string `json:"command"`
}

type BashResponse struct {
	Output  string `json:"output"`
	Success bool   `json:"success"`
}

type BuildResponse struct {
	Build   json.RawMessage `json:"build"`
	Success bool            `json:"success"`
}

type ClickRequest struct {
	Button string `json:"button"`
	Double bool   `json:"double"`
	X      int    `json:"x"`
	Y      int    `json:"y"`
}

type CloneComputerResponse struct {
	Id     string `json:"id"`
	Name   string `json:"name"`
	Status string `json:"status"`
}

type Computer struct {
	ConnectionUrl string `json:"connection_url"`
	Cpu           int    `json:"cpu"`
	CreatedAt     string `json:"created_at"`
	DiskSizeGb    int    `json:"disk_size_gb"`
	FlyInstanceId string `json:"fly_instance_id"`
	Hostname      string `json:"hostname"`
	Id            string `json:"id"`
	Name          string `json:"name"`
	Os            string `json:"os"`
	ProjectName   string `json:"project_name"`
	Ram           int    `json:"ram"`
	Status        string `json:"status"`
	Url           string `json:"url"`
	VncPassword   string `json:"vnc_password"`
}

type ComputersDeleteResponse struct {
	Success bool `json:"success"`
}

type CreateBuildRequest struct {
	Name      string `json:"name"`
	OrgId     string `json:"orgId"`
	ProjectId string `json:"projectId"`
}

type CreateComputerRequest struct {
	AutoStopMinutes int    `json:"auto_stop_minutes"`
	Cpu             int    `json:"cpu"`
	DiskSizeGb      int    `json:"disk_size_gb"`
	Image           string `json:"image"`
	Name            string `json:"name"`
	Os              string `json:"os"`
	Ram             int    `json:"ram"`
	Resolution      string `json:"resolution"`
	WorkspaceId     string `json:"workspace_id"`
}

type DragRequest struct {
	Button   string  `json:"button"`
	Duration float64 `json:"duration"`
	EndX     int     `json:"end_x"`
	EndY     int     `json:"end_y"`
	StartX   int     `json:"start_x"`
	StartY   int     `json:"start_y"`
}

type Error struct {
	Error string `json:"error"`
}

type ExecRequest struct {
	Code    string `json:"code"`
	Timeout int    `json:"timeout"`
}

type ExecResponse struct {
	Error     string `json:"error"`
	ErrorType string `json:"error_type"`
	Output    string `json:"output"`
	Success   bool   `json:"success"`
	Timeout   bool   `json:"timeout"`
}

type File struct {
	ContentType string `json:"content_type"`
	CreatedAt   string `json:"created_at"`
	Filename    string `json:"filename"`
	Id          string `json:"id"`
	SizeBytes   int    `json:"size_bytes"`
}

type FileDownloadResponse struct {
	Url string `json:"url"`
}

type FileExportRequest struct {
	DesktopId string `json:"desktopId"`
	Path      string `json:"path"`
}

type FileExportResponse struct {
	File    json.RawMessage `json:"file"`
	Success bool            `json:"success"`
	Url     string          `json:"url"`
}

type FileListResponse struct {
	Files json.RawMessage `json:"files"`
}

type FileUploadResponse struct {
	File json.RawMessage `json:"file"`
}

type FilesDeleteResponse struct {
	Success bool `json:"success"`
}

type KeyRequest struct {
	Key string `json:"key"`
}

type MoveComputerResponse struct {
	ProjectId string `json:"project_id"`
	Success   bool   `json:"success"`
}

type ResizeComputerResponse struct {
	BandwidthLimitMbps int `json:"bandwidth_limit_mbps"`
	DiskSizeGb         int `json:"disk_size_gb"`
	MemGb              int `json:"mem_gb"`
	Vcpus              int `json:"vcpus"`
}

type RestartComputerResponse struct {
	Status  string `json:"status"`
	Success bool   `json:"success"`
}

type ScreenshotGetResponse struct {
	Image string `json:"image"`
}

type ScrollRequest struct {
	Amount    int    `json:"amount"`
	Direction string `json:"direction"`
}

type StartComputerResponse struct {
	Status  string `json:"status"`
	Success bool   `json:"success"`
}

type StopComputerResponse struct {
	Status  string `json:"status"`
	Success bool   `json:"success"`
}

type StreamStartRequest struct {
	ConnectionName string `json:"connection_name"`
}

type StreamStartResponse struct {
	Pid     int    `json:"pid"`
	Status  string `json:"status"`
	Success bool   `json:"success"`
}

type StreamStatusResponse struct {
	Pid       int    `json:"pid"`
	StartTime string `json:"start_time"`
	Status    string `json:"status"`
}

type StreamStopResponse struct {
	Success bool `json:"success"`
}

type TypeRequest struct {
	Text string `json:"text"`
}

type UpdateBuildRequest struct {
	BuildId      string `json:"buildId"`
	ErrorMessage string `json:"errorMessage"`
	Logs         string `json:"logs"`
	Status       string `json:"status"`
}

type VncPasswordGetResponse struct {
	Password string `json:"password"`
}

type WaitRequest struct {
	Duration float64 `json:"duration"`
}

type Workspace struct {
	CreatedAt string `json:"created_at"`
	IconUrl   string `json:"icon_url"`
	Id        string `json:"id"`
	Name      string `json:"name"`
	Status    string `json:"status"`
	UpdatedAt string `json:"updated_at"`
	UserId    string `json:"user_id"`
}

type WorkspaceWithDesktops struct {
	CreatedAt string          `json:"created_at"`
	Desktops  json.RawMessage `json:"desktops"`
	IconUrl   string          `json:"icon_url"`
	Id        string          `json:"id"`
	Name      string          `json:"name"`
	Status    string          `json:"status"`
	UpdatedAt string          `json:"updated_at"`
	UserId    string          `json:"user_id"`
}

type WorkspacesDeleteResponse struct {
	Success bool `json:"success"`
}

type WorkspacesListResponse struct {
	Workspaces json.RawMessage `json:"workspaces"`
}
