// Package chrome ships DOM-aware Chrome automation as a transcendence command
// set on top of the printed Orgo CLI. It is NOT generated by the Printing Press
// — it's hand-built domain logic that the machine cannot produce from the
// upstream OpenAPI spec, modeled after orgo-chrome-mcp
// (https://github.com/nickvasilescu/orgo-chrome-mcp).
//
// Architecture: each chrome command resolves to a JSON-over-HTTP call to a
// per-VM Node bridge listening on 127.0.0.1:7331 inside the Orgo VM. The
// bridge is deployed on first use via bash + base64 round-trip, then exposes
// the 16-tool DOM surface (navigate/read_page/find/click/type/etc.) over
// HTTP. Calls reach the bridge by wrapping a curl in the existing
// /computers/{id}/bash channel, so VM-direct routing inherits transparently
// from the Client (--vm-from / --vm-url / --vm-token).
package chrome

import (
	"context"
	"crypto/sha256"
	_ "embed"
	"encoding/base64"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"strings"
	"time"
)

//go:embed bridge/orgo-chrome-bridge.js
var bridgeScript []byte

// bridgeHash is the SHA256 hex digest of the embedded bridge JS. It's written
// to /tmp/orgo-chrome-bridge.hash after a successful deploy and compared on
// each call so a CLI upgrade triggers a redeploy on long-lived VMs running
// an older bridge.
var bridgeHash = computeBridgeHash()

func computeBridgeHash() string {
	sum := sha256.Sum256(bridgeScript)
	return hex.EncodeToString(sum[:])
}

const (
	bridgePort       = 7331
	bridgeScriptPath = "/tmp/orgo-chrome-bridge.js"
	bridgeHashPath   = "/tmp/orgo-chrome-bridge.hash"
	bridgeLogPath    = "/tmp/orgo-chrome-bridge.log"

	deployTimeout = 30 * time.Second
)

// BashFunc executes a bash command on an Orgo VM and returns combined stdout.
// The implementation is expected to route through /computers/{id}/bash on the
// central API or directly to the per-VM agent when VM-direct routing is set.
type BashFunc func(ctx context.Context, computerID, command string) (string, error)

// Manager owns the deploy-and-call cycle for the in-VM chrome bridge.
// One Manager per chrome command invocation is fine — state lives inside the
// VM, not in this struct.
type Manager struct {
	Bash BashFunc
}

// Call invokes a bridge endpoint and returns the JSON response. It deploys
// the bridge first if /health is unreachable or the running bridge's hash
// differs from the embedded one.
//
// method is "GET" or "POST"; body is marshalled to JSON for POSTs (ignored
// otherwise). The bridge's own response is JSON; this function returns the
// raw bytes so callers can decode into their own shapes.
func (m *Manager) Call(ctx context.Context, computerID, method, path string, body any) (json.RawMessage, error) {
	if err := m.EnsureBridge(ctx, computerID); err != nil {
		return nil, err
	}
	return m.rawCall(ctx, computerID, method, path, body)
}

// rawCall sends a single request to the bridge without an EnsureBridge guard.
// Used by EnsureBridge itself (health/version probes) to avoid recursion.
func (m *Manager) rawCall(ctx context.Context, computerID, method, path string, body any) (json.RawMessage, error) {
	var curl string
	switch strings.ToUpper(method) {
	case "GET":
		curl = fmt.Sprintf("curl -sf http://127.0.0.1:%d%s", bridgePort, path)
	case "POST":
		payload, err := json.Marshal(body)
		if err != nil {
			return nil, fmt.Errorf("marshalling body: %w", err)
		}
		if body == nil {
			payload = []byte("{}")
		}
		curl = fmt.Sprintf(
			"curl -sf -X POST http://127.0.0.1:%d%s -H 'Content-Type: application/json' --data-binary @- <<'ORGO_CHROME_BODY'\n%s\nORGO_CHROME_BODY",
			bridgePort, path, string(payload),
		)
	default:
		return nil, fmt.Errorf("unsupported method %q", method)
	}

	out, err := m.Bash(ctx, computerID, curl)
	if err != nil {
		return nil, fmt.Errorf("bridge call %s %s: %w", method, path, err)
	}
	out = strings.TrimSpace(out)
	if out == "" {
		return nil, fmt.Errorf("bridge returned empty response for %s %s", method, path)
	}
	if !json.Valid([]byte(out)) {
		if i := strings.IndexByte(out, '{'); i >= 0 && json.Valid([]byte(out[i:])) {
			out = out[i:]
		} else {
			head := out
			if len(head) > 300 {
				head = head[:300] + "..."
			}
			return nil, fmt.Errorf("bridge returned non-JSON for %s %s: %s", method, path, head)
		}
	}
	return json.RawMessage(out), nil
}

// EnsureBridge probes the bridge and redeploys when it's down or stale.
// "Stale" = the hash file in the VM doesn't match the embedded bridge hash.
// Returns nil when a healthy, matching bridge is reachable.
func (m *Manager) EnsureBridge(ctx context.Context, computerID string) error {
	probe := fmt.Sprintf(
		"curl -sf http://127.0.0.1:%d/health 2>/dev/null || echo '{\"status\":\"down\"}'",
		bridgePort,
	)
	out, err := m.Bash(ctx, computerID, probe)
	if err != nil {
		return fmt.Errorf("probing bridge: %w", err)
	}
	out = strings.TrimSpace(out)
	var health struct {
		Status string `json:"status"`
	}
	if err := json.Unmarshal([]byte(out), &health); err == nil && health.Status == "ok" {
		hash, _ := m.Bash(ctx, computerID, "cat "+bridgeHashPath+" 2>/dev/null || true")
		if strings.TrimSpace(hash) == bridgeHash {
			return nil
		}
	}
	return m.deploy(ctx, computerID)
}

// deploy uploads the bridge script via base64 round-trip, starts it under
// DISPLAY=:99, and polls /health for up to deployTimeout. base64 avoids the
// shell-quoting hazards of a heredoc with arbitrary JS source.
func (m *Manager) deploy(ctx context.Context, computerID string) error {
	if _, err := m.Bash(ctx, computerID,
		"pkill -f 'node "+bridgeScriptPath+"' 2>/dev/null || true ; "+
			"rm -f /tmp/chrome-cdp-profile/SingletonLock /tmp/chrome-cdp-profile/SingletonSocket 2>/dev/null || true",
	); err != nil {
		return fmt.Errorf("clearing prior bridge: %w", err)
	}

	enc := base64.StdEncoding.EncodeToString(bridgeScript)
	upload := fmt.Sprintf(
		"echo %s | base64 -d > %s && echo -n %s > %s",
		enc, bridgeScriptPath, bridgeHash, bridgeHashPath,
	)
	if _, err := m.Bash(ctx, computerID, upload); err != nil {
		return fmt.Errorf("uploading bridge: %w", err)
	}

	start := fmt.Sprintf(
		"DISPLAY=:99 nohup node %s > %s 2>&1 < /dev/null & disown ; sleep 0.2 ; true",
		bridgeScriptPath, bridgeLogPath,
	)
	if _, err := m.Bash(ctx, computerID, start); err != nil {
		return fmt.Errorf("starting bridge: %w", err)
	}

	deadline := time.Now().Add(deployTimeout)
	for time.Now().Before(deadline) {
		select {
		case <-ctx.Done():
			return ctx.Err()
		case <-time.After(750 * time.Millisecond):
		}
		out, err := m.Bash(ctx, computerID,
			fmt.Sprintf("curl -sf http://127.0.0.1:%d/health 2>/dev/null || echo '{}'", bridgePort),
		)
		if err != nil {
			continue
		}
		var health struct {
			Status string `json:"status"`
		}
		if json.Unmarshal([]byte(strings.TrimSpace(out)), &health) == nil && health.Status == "ok" {
			return nil
		}
	}

	tail, _ := m.Bash(ctx, computerID, "tail -50 "+bridgeLogPath+" 2>/dev/null || echo '(no log)'")
	return fmt.Errorf("bridge failed to become healthy within %s. Recent log:\n%s", deployTimeout, tail)
}
