// Copyright 2026 nickvasilescu. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package mcp

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	mcplib "github.com/mark3labs/mcp-go/mcp"
	"github.com/mark3labs/mcp-go/server"
	"github.com/nickvasilescu/orgo-pp-cli/internal/cli"
	"github.com/nickvasilescu/orgo-pp-cli/internal/client"
	"github.com/nickvasilescu/orgo-pp-cli/internal/cliutil"
	"github.com/nickvasilescu/orgo-pp-cli/internal/config"
	"github.com/nickvasilescu/orgo-pp-cli/internal/mcp/cobratree"
	"github.com/nickvasilescu/orgo-pp-cli/internal/store"
)

// RegisterTools registers all API operations as MCP tools.
func RegisterTools(s *server.MCPServer) {
	s.AddTool(
		mcplib.NewTool("computers_create",
			mcplib.WithDescription("Creates a new virtual computer in a workspace. The computer starts automatically after creation. Required: name, workspace_id. Optional: auto_stop_minutes, cpu (default: 1), disk_size_gb (default: 8) (plus 4 more). Returns the new Computer."),
			mcplib.WithString("auto_stop_minutes", mcplib.Description("Auto-stop after this many minutes of inactivity. Set to 0 to disable. Free tier locked to 15 minutes.")),
			mcplib.WithString("cpu", mcplib.Description("CPU cores. Capped by plan.")),
			mcplib.WithString("disk_size_gb", mcplib.Description("Disk size in GB. Capped by plan.")),
			mcplib.WithString("image", mcplib.Description("Custom Docker image reference. Use with templates built via the SDK.")),
			mcplib.WithString("name", mcplib.Required(), mcplib.Description("Computer name")),
			mcplib.WithString("os", mcplib.Description("Operating system")),
			mcplib.WithString("ram", mcplib.Description("RAM in GB. Capped by plan.")),
			mcplib.WithString("resolution", mcplib.Description("Display resolution in WIDTHxHEIGHTxDEPTH format")),
			mcplib.WithString("workspace_id", mcplib.Required(), mcplib.Description("ID of the workspace to create the computer in")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/computers", []mcpParamBinding{{PublicName: "auto_stop_minutes", WireName: "auto_stop_minutes", Location: "body"}, {PublicName: "cpu", WireName: "cpu", Location: "body"}, {PublicName: "disk_size_gb", WireName: "disk_size_gb", Location: "body"}, {PublicName: "image", WireName: "image", Location: "body"}, {PublicName: "name", WireName: "name", Location: "body"}, {PublicName: "os", WireName: "os", Location: "body"}, {PublicName: "ram", WireName: "ram", Location: "body"}, {PublicName: "resolution", WireName: "resolution", Location: "body"}, {PublicName: "workspace_id", WireName: "workspace_id", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("computers_delete",
			mcplib.WithDescription("Permanently deletes a computer and all its data. Required: id. Returns the ComputersDeleteResponse. Destructive."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("Computer ID")),
			mcplib.WithDestructiveHintAnnotation(true),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("DELETE", "/computers/{id}", []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("computers_get",
			mcplib.WithDescription("Returns computer details including current status. Required: id."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("Computer ID")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/computers/{id}", []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("computers_auto-stop_get",
			mcplib.WithDescription("Returns the current auto-stop configuration for a computer. Required: id."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("Computer ID")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/computers/{id}/auto-stop", []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("computers_auto-stop_update",
			mcplib.WithDescription("Updates the auto-stop setting for a computer. Paid plans only — free tier is fixed at 15 minutes. Required: id, auto_stop_minutes. Returns the updated AutoStopUpdateResponse."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("Computer ID")),
			mcplib.WithString("auto_stop_minutes", mcplib.Required(), mcplib.Description("Minutes of inactivity before auto-stop. Set to 0 to disable.")),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("PATCH", "/computers/{id}/auto-stop", []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}, {PublicName: "auto_stop_minutes", WireName: "auto_stop_minutes", Location: "body"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("computers_bash_execute",
			mcplib.WithDescription("Executes a bash command on the computer. Required: id, command. Returns the new BashResponse."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("Computer ID")),
			mcplib.WithString("command", mcplib.Required(), mcplib.Description("Bash command to execute")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/computers/{id}/bash", []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}, {PublicName: "command", WireName: "command", Location: "body"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("computers_click_mouse",
			mcplib.WithDescription("Performs a mouse click at the specified coordinates. Required: id, x, y. Optional: button (default: left), double (default: false). Returns the new ActionResponse."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("Computer ID")),
			mcplib.WithString("button", mcplib.Description("Mouse button")),
			mcplib.WithString("double", mcplib.Description("Double-click")),
			mcplib.WithString("x", mcplib.Required(), mcplib.Description("X coordinate")),
			mcplib.WithString("y", mcplib.Required(), mcplib.Description("Y coordinate")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/computers/{id}/click", []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}, {PublicName: "button", WireName: "button", Location: "body"}, {PublicName: "double", WireName: "double", Location: "body"}, {PublicName: "x", WireName: "x", Location: "body"}, {PublicName: "y", WireName: "y", Location: "body"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("computers_clone_computer",
			mcplib.WithDescription("Creates a copy of a computer with the same disk state. Counts toward your plan's computer limit. Required: id. Returns the new CloneComputerResponse."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("Source computer ID")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/computers/{id}/clone", []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("computers_drag_mouse",
			mcplib.WithDescription("Performs a mouse drag from start to end coordinates. Required: id, end_x, end_y, start_x, start_y. Optional: button (default: left), duration (default: 0.5). Returns the new ActionResponse."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("Computer ID")),
			mcplib.WithString("button", mcplib.Description("Mouse button")),
			mcplib.WithString("duration", mcplib.Description("Drag duration in seconds")),
			mcplib.WithString("end_x", mcplib.Required(), mcplib.Description("End X coordinate")),
			mcplib.WithString("end_y", mcplib.Required(), mcplib.Description("End Y coordinate")),
			mcplib.WithString("start_x", mcplib.Required(), mcplib.Description("Start X coordinate")),
			mcplib.WithString("start_y", mcplib.Required(), mcplib.Description("Start Y coordinate")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/computers/{id}/drag", []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}, {PublicName: "button", WireName: "button", Location: "body"}, {PublicName: "duration", WireName: "duration", Location: "body"}, {PublicName: "end_x", WireName: "end_x", Location: "body"}, {PublicName: "end_y", WireName: "end_y", Location: "body"}, {PublicName: "start_x", WireName: "start_x", Location: "body"}, {PublicName: "start_y", WireName: "start_y", Location: "body"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("computers_exec_execute-python",
			mcplib.WithDescription("Executes Python code on the computer. Required: id, code. Optional: timeout (default: 10). Returns the new ExecResponse."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("Computer ID")),
			mcplib.WithString("code", mcplib.Required(), mcplib.Description("Python code to execute")),
			mcplib.WithString("timeout", mcplib.Description("Timeout in seconds")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/computers/{id}/exec", []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}, {PublicName: "code", WireName: "code", Location: "body"}, {PublicName: "timeout", WireName: "timeout", Location: "body"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("computers_key_press",
			mcplib.WithDescription("Presses a key or key combination (e.g., Enter, Tab, ctrl+c). Required: id, key. Returns the new ActionResponse."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("Computer ID")),
			mcplib.WithString("key", mcplib.Required(), mcplib.Description("Key or key combination (e.g., Enter, Tab, ctrl+c, alt+F4)")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/computers/{id}/key", []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}, {PublicName: "key", WireName: "key", Location: "body"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("computers_move_computer",
			mcplib.WithDescription("Moves a computer to a different workspace. Both source and destination must be owned by you. Required: id, project_id. Returns the updated MoveComputerResponse."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("Computer ID")),
			mcplib.WithString("project_id", mcplib.Required(), mcplib.Description("Destination workspace ID")),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("PATCH", "/computers/{id}/move", []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}, {PublicName: "project_id", WireName: "project_id", Location: "body"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("computers_resize_computer",
			mcplib.WithDescription("Live-resizes a running computer's CPU, RAM, disk, or bandwidth. All fields optional — only include what you want to change. Required: id. Optional: bandwidth_limit_mbps, disk_size_gb, mem_gb (plus 1 more). Returns the updated ResizeComputerResponse."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("Computer ID")),
			mcplib.WithString("bandwidth_limit_mbps", mcplib.Description("New bandwidth cap in Mbps. Capped by plan.")),
			mcplib.WithString("disk_size_gb", mcplib.Description("New disk size in GB. Grow only — shrinking not supported.")),
			mcplib.WithString("mem_gb", mcplib.Description("New RAM in GB. Capped by plan.")),
			mcplib.WithString("vcpus", mcplib.Description("New CPU count. Capped by plan.")),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("PATCH", "/computers/{id}/resize", []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}, {PublicName: "bandwidth_limit_mbps", WireName: "bandwidth_limit_mbps", Location: "body"}, {PublicName: "disk_size_gb", WireName: "disk_size_gb", Location: "body"}, {PublicName: "mem_gb", WireName: "mem_gb", Location: "body"}, {PublicName: "vcpus", WireName: "vcpus", Location: "body"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("computers_restart_computer",
			mcplib.WithDescription("Restarts a computer. Equivalent to stop + start. Required: id. Returns the new RestartComputerResponse."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("Computer ID")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/computers/{id}/restart", []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("computers_screenshot_get",
			mcplib.WithDescription("Captures a screenshot of the computer display. Returns base64-encoded PNG or a URL. Required: id."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("Computer ID")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/computers/{id}/screenshot", []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("computers_scroll_scroll",
			mcplib.WithDescription("Scrolls the mouse wheel up or down. Required: id, direction. Optional: amount (default: 3). Returns the new ActionResponse."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("Computer ID")),
			mcplib.WithString("amount", mcplib.Description("Scroll amount (clicks)")),
			mcplib.WithString("direction", mcplib.Required(), mcplib.Description("Scroll direction")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/computers/{id}/scroll", []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}, {PublicName: "amount", WireName: "amount", Location: "body"}, {PublicName: "direction", WireName: "direction", Location: "body"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("computers_start_computer",
			mcplib.WithDescription("Starts a stopped computer. Computers auto-stop after inactivity. Required: id. Returns the new StartComputerResponse."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("Computer ID")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/computers/{id}/start", []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("computers_stop_computer",
			mcplib.WithDescription("Stops a running computer. State is preserved. Required: id. Returns the new StopComputerResponse."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("Computer ID")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/computers/{id}/stop", []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("computers_stream_get-status",
			mcplib.WithDescription("Get the current RTMP display-stream status for a computer. Required: id (computer ID). Returns a status enum (idle, streaming, terminated), the streamer process start_time, and the streamer pid. Use this to check whether computers_stream_start succeeded and the framebuffer is currently being broadcast before reading network traffic with computers_screenshot or starting a recorder."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("Computer ID")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/computers/{id}/stream/status", []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("computers_stream_start",
			mcplib.WithDescription("Starts streaming the computer display via RTMP to a configured connection. Required: id, connection_name. Returns the new StreamStartResponse."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("Computer ID")),
			mcplib.WithString("connection_name", mcplib.Required(), mcplib.Description("Name of the configured RTMP connection")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/computers/{id}/stream/start", []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}, {PublicName: "connection_name", WireName: "connection_name", Location: "body"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("computers_stream_stop",
			mcplib.WithDescription("Stops the active RTMP stream. Required: id. Returns the new StreamStopResponse."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("Computer ID")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/computers/{id}/stream/stop", []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("computers_type_text",
			mcplib.WithDescription("Types text on the computer keyboard. Required: id, text. Returns the new ActionResponse."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("Computer ID")),
			mcplib.WithString("text", mcplib.Required(), mcplib.Description("Text to type")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/computers/{id}/type", []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}, {PublicName: "text", WireName: "text", Location: "body"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("computers_vnc-password_get",
			mcplib.WithDescription("Returns the VNC password for direct VNC connection to the computer. Only accessible by workspace owners and members. Required: id."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("Computer ID")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/computers/{id}/vnc-password", []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("computers_wait_wait",
			mcplib.WithDescription("Pauses execution for the specified duration. Required: id, duration. Returns the new ActionResponse."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("Computer ID")),
			mcplib.WithString("duration", mcplib.Required(), mcplib.Description("Duration in seconds")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/computers/{id}/wait", []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}, {PublicName: "duration", WireName: "duration", Location: "body"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("files_delete",
			mcplib.WithDescription("Permanently deletes a file from storage. Required: id. Returns the FilesDeleteResponse. Destructive."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("File ID")),
			mcplib.WithDestructiveHintAnnotation(true),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("DELETE", "/files/delete", []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("files_download",
			mcplib.WithDescription("Returns a signed download URL for a file. URLs expire in 1 hour. Required: id."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("File ID")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/files/download", []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("files_export",
			mcplib.WithDescription("Exports a file from the computer's filesystem and returns a download URL. Required: desktopId, path."),
			mcplib.WithString("desktopId", mcplib.Required(), mcplib.Description("Computer ID")),
			mcplib.WithString("path", mcplib.Required(), mcplib.Description("Path to file on computer (e.g., Desktop/results.txt)")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/files/export", []mcpParamBinding{{PublicName: "desktopId", WireName: "desktopId", Location: "body"}, {PublicName: "path", WireName: "path", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("files_list",
			mcplib.WithDescription("Lists all files in a workspace, optionally filtered by computer. Required: projectId. Optional: desktopId. Returns the FileListResponse."),
			mcplib.WithString("projectId", mcplib.Required(), mcplib.Description("Workspace ID")),
			mcplib.WithString("desktopId", mcplib.Description("Optional computer ID to filter by")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/files", []mcpParamBinding{{PublicName: "projectId", WireName: "projectId", Location: "query"}, {PublicName: "desktopId", WireName: "desktopId", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("files_upload",
			mcplib.WithDescription("Uploads a file to a workspace. Maximum file size is 10MB. Required: file, projectId. Optional: desktopId. Returns the new FileUploadResponse."),
			mcplib.WithString("desktopId", mcplib.Description("Optional computer ID to associate the file with")),
			mcplib.WithString("file", mcplib.Required(), mcplib.Description("File to upload (max 10MB)")),
			mcplib.WithString("projectId", mcplib.Required(), mcplib.Description("Workspace ID")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/files/upload", []mcpParamBinding{{PublicName: "desktopId", WireName: "desktopId", Location: "body"}, {PublicName: "file", WireName: "file", Location: "body"}, {PublicName: "projectId", WireName: "projectId", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("workspaces_create",
			mcplib.WithDescription("Creates a new workspace. Workspace names must be unique per user. Required: name. Optional: icon_url, status (default: active). Returns the new Workspace."),
			mcplib.WithString("icon_url", mcplib.Description("Optional icon URL")),
			mcplib.WithString("name", mcplib.Required(), mcplib.Description("Workspace name. Must be unique within your account.")),
			mcplib.WithString("status", mcplib.Description("Status")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/workspaces", []mcpParamBinding{{PublicName: "icon_url", WireName: "icon_url", Location: "body"}, {PublicName: "name", WireName: "name", Location: "body"}, {PublicName: "status", WireName: "status", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("workspaces_delete",
			mcplib.WithDescription("Deletes a workspace and all its computers. This action cannot be undone. Required: id. Returns the WorkspacesDeleteResponse. Destructive."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("Workspace ID")),
			mcplib.WithDestructiveHintAnnotation(true),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("DELETE", "/workspaces/{id}", []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("workspaces_get",
			mcplib.WithDescription("Returns a workspace by ID, including its computers. Required: id."),
			mcplib.WithString("id", mcplib.Required(), mcplib.Description("Workspace ID")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/workspaces/{id}", []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "path"}}, []string{"id"}),
	)
	s.AddTool(
		mcplib.NewTool("workspaces_list",
			mcplib.WithDescription("List all workspaces owned by the authenticated user. Returns an array of workspace objects, each with id, name, user_id, status (active|inactive), icon_url, created_at, and updated_at. Workspaces are the top-level container for computers; use this to discover the workspace id you pass to computers_create or computers_list. No parameters; the response is not paginated."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/workspaces", []mcpParamBinding{}, []string{}),
	)
	// Search tool — faster than iterating list endpoints for finding specific items
	s.AddTool(
		mcplib.NewTool("search",
			mcplib.WithDescription("Full-text search across all synced data. Faster than paginating list endpoints. Requires sync first."),
			mcplib.WithString("query", mcplib.Required(), mcplib.Description("Search query (supports FTS5 syntax: AND, OR, NOT, quotes for phrases)")),
			mcplib.WithNumber("limit", mcplib.Description("Max results (default 25)")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		handleSearch,
	)
	// SQL tool — ad-hoc analysis on synced data without API calls
	s.AddTool(
		mcplib.NewTool("sql",
			mcplib.WithDescription("Run read-only SQL against local database. Use for ad-hoc analysis, aggregations, and joins across synced resources. Requires sync first."),
			mcplib.WithString("query", mcplib.Required(), mcplib.Description("SQL query (SELECT or WITH...SELECT). Tables match resource names.")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		handleSQL,
	)

	// Context tool — front-loaded domain knowledge for agents.
	// Call this first to understand the API taxonomy, query patterns, and capabilities.
	s.AddTool(
		mcplib.NewTool("context",
			mcplib.WithDescription("Get API domain context: resource taxonomy, auth requirements, query tips, and unique capabilities. Call this first."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		handleContext,
	)

	// Runtime Cobra-tree mirror — exposes every user-facing command that is
	// not already covered by a typed endpoint or framework MCP tool.
	cobratree.RegisterAll(s, cli.RootCmd(), cobratree.SiblingCLIPath)
}

type mcpParamBinding struct {
	PublicName string
	WireName   string
	Location   string
}

// makeAPIHandler creates a generic MCP tool handler for an API endpoint.
func makeAPIHandler(method, pathTemplate string, bindings []mcpParamBinding, positionalParams []string) server.ToolHandlerFunc {
	return func(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
		c, err := newMCPClient()
		if err != nil {
			return mcplib.NewToolResultError(err.Error()), nil
		}

		// mcp-go v0.47+ made CallToolParams.Arguments an `any` to support
		// non-map payloads; GetArguments() returns the map[string]any shape
		// we rely on here (or an empty map when the payload is something else).
		args := req.GetArguments()

		// positionalParams mixes real URL path params with CLI positional
		// args that map to query params (e.g. `search <query>` -> ?query=);
		// the placeholder check below disambiguates them at runtime.
		path := pathTemplate
		knownArgs := make(map[string]bool, len(bindings))
		pathParams := make(map[string]bool, len(positionalParams))
		params := make(map[string]string)
		bodyArgs := make(map[string]any)
		for _, binding := range bindings {
			knownArgs[binding.PublicName] = true
			v, ok := args[binding.PublicName]
			if !ok {
				continue
			}
			switch binding.Location {
			case "path":
				placeholder := "{" + binding.WireName + "}"
				pathParams[binding.PublicName] = true
				path = strings.Replace(path, placeholder, fmt.Sprintf("%v", v), 1)
			case "body":
				bodyArgs[binding.WireName] = v
			default:
				params[binding.WireName] = fmt.Sprintf("%v", v)
			}
		}
		for _, p := range positionalParams {
			placeholder := "{" + p + "}"
			if !strings.Contains(pathTemplate, placeholder) {
				continue
			}
			pathParams[p] = true
			if v, ok := args[p]; ok {
				path = strings.Replace(path, placeholder, fmt.Sprintf("%v", v), 1)
			}
		}

		for k, v := range args {
			if pathParams[k] || knownArgs[k] {
				continue
			}
			switch method {
			case "POST", "PUT", "PATCH":
				bodyArgs[k] = v
			default:
				params[k] = fmt.Sprintf("%v", v)
			}
		}

		var data json.RawMessage
		switch method {
		case "GET":
			data, err = c.Get(path, params)
		case "POST":
			body, _ := json.Marshal(bodyArgs)
			data, _, err = c.Post(path, body)
		case "PUT":
			body, _ := json.Marshal(bodyArgs)
			data, _, err = c.Put(path, body)
		case "PATCH":
			body, _ := json.Marshal(bodyArgs)
			data, _, err = c.Patch(path, body)
		case "DELETE":
			data, _, err = c.Delete(path)
		default:
			return mcplib.NewToolResultError("unsupported method: " + method), nil
		}

		if err != nil {
			msg := err.Error()
			switch {
			case strings.Contains(msg, "HTTP 409"):
				return mcplib.NewToolResultText("already exists (no-op)"), nil
			case strings.Contains(msg, "HTTP 400") && cliutil.LooksLikeAuthError(msg):
				return mcplib.NewToolResultError("authentication error: " + cliutil.SanitizeErrorBody(msg) +
					"\nhint: the API rejected the request — this usually means auth is missing or invalid." +
					"\n      Set your API key: export ORGO_API_KEY=<your-key>" +
					"\n      Run 'orgo-pp-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 401"):
				return mcplib.NewToolResultError("authentication failed: " + cliutil.SanitizeErrorBody(msg) +
					"\nhint: check your token." +
					"\n      Set it with: export ORGO_API_KEY=<your-key>" +
					"\n      Run 'orgo-pp-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 403"):
				return mcplib.NewToolResultError("permission denied: " + cliutil.SanitizeErrorBody(msg) +
					"\nhint: your credentials are valid but lack access to this resource." +
					"\n      Set it with: export ORGO_API_KEY=<your-key>" +
					"\n      Run 'orgo-pp-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 404"):
				if method == "DELETE" {
					return mcplib.NewToolResultText("already deleted (no-op)"), nil
				}
				return mcplib.NewToolResultError("not found: " + msg), nil
			case strings.Contains(msg, "HTTP 429"):
				return mcplib.NewToolResultError("rate limited: " + msg), nil
			default:
				return mcplib.NewToolResultError(msg), nil
			}
		}

		// For GET responses, wrap bare arrays with count metadata
		if method == "GET" {
			trimmed := strings.TrimSpace(string(data))
			if len(trimmed) > 0 && trimmed[0] == '[' {
				var items []json.RawMessage
				if json.Unmarshal(data, &items) == nil {
					wrapped := map[string]any{
						"count": len(items),
						"items": items,
					}
					out, _ := json.Marshal(wrapped)
					return mcplib.NewToolResultText(string(out)), nil
				}
			}
		}
		return mcplib.NewToolResultText(string(data)), nil
	}
}

func newMCPClient() (*client.Client, error) {
	home, _ := os.UserHomeDir()
	cfgPath := filepath.Join(home, ".config", "orgo-pp-cli", "config.toml")
	cfg, err := config.Load(cfgPath)
	if err != nil {
		return nil, fmt.Errorf("loading config: %w", err)
	}
	c := client.New(cfg, 30*time.Second, 0)
	// Agents calling through MCP need fresh data every call. The on-disk
	// response cache survives across MCP server invocations, so a
	// DELETE/PATCH followed by a GET would otherwise return the
	// pre-mutation snapshot for up to the cache TTL. The interactive CLI
	// constructs its own client and is unaffected.
	c.NoCache = true
	return c, nil
}

func dbPath() string {
	home, _ := os.UserHomeDir()
	return filepath.Join(home, ".local", "share", "orgo-pp-cli", "data.db")
}

// Note: MCP tools use their own dbPath() because they are in a separate package (main, not cli).
// The CLI's defaultDBPath() in the cli package uses the same canonical path.

func handleSearch(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	args := req.GetArguments()
	query, ok := args["query"].(string)
	if !ok || query == "" {
		return mcplib.NewToolResultError("query is required"), nil
	}

	limit := 25
	if v, ok := args["limit"].(float64); ok && v > 0 {
		limit = int(v)
	}

	db, err := store.OpenReadOnly(dbPath())
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("opening database: %v", err)), nil
	}
	defer db.Close()

	results, err := db.Search(query, limit)
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("search failed: %v", err)), nil
	}

	data, _ := json.MarshalIndent(results, "", "  ")
	return mcplib.NewToolResultText(string(data)), nil
}

// validateReadOnlyQuery gates the MCP sql tool. The agent contract advertised
// to the host is ReadOnlyHintAnnotation(true); a false annotation on a
// mutating tool lets MCP hosts auto-approve writes and is treated as a real
// bug per the project's agent-native security model.
//
// The gate is an allowlist (SELECT or WITH only) applied AFTER stripping the
// leading whitespace, line comments, block comments, and semicolons that
// SQLite itself ignores before parsing. A naive HasPrefix check on a
// keyword blocklist is bypassable by prefixing the dangerous statement with
// "/* x */" or "-- x\n" — TrimSpace strips outer whitespace but does not
// understand SQL comment syntax. Combined with the empirical fact that
// modernc.org/sqlite's mode=ro does NOT block VACUUM INTO (writes a snapshot
// to a new file) or ATTACH DATABASE (opens a separate writable handle),
// such a bypass produces silent exfiltration to an attacker-chosen path.
//
// SELECT and WITH are the only allowed leading keywords. WITH supports
// SELECT-form CTEs; CTE-wrapped writes ("WITH x AS (...) INSERT ...") are
// caught by OpenReadOnly's mode=ro one layer down. PRAGMA, ATTACH, VACUUM,
// and every other DDL/DML keyword fail at this gate before reaching SQLite.
func validateReadOnlyQuery(query string) error {
	upper := strings.ToUpper(stripLeadingSQLNoise(query))
	if !strings.HasPrefix(upper, "SELECT") && !strings.HasPrefix(upper, "WITH") {
		return fmt.Errorf("only SELECT queries are allowed")
	}
	return nil
}

// stripLeadingSQLNoise removes leading whitespace, SQL line comments
// (-- to end of line), block comments (/* ... */), and statement
// separators (;) from query. SQLite skips these before parsing the first
// keyword, so a security gate that does not strip them mismatches what the
// driver actually executes.
func stripLeadingSQLNoise(query string) string {
	for {
		query = strings.TrimLeft(query, " \t\r\n;")
		switch {
		case strings.HasPrefix(query, "--"):
			if idx := strings.IndexByte(query, '\n'); idx >= 0 {
				query = query[idx+1:]
				continue
			}
			return ""
		case strings.HasPrefix(query, "/*"):
			if idx := strings.Index(query[2:], "*/"); idx >= 0 {
				query = query[2+idx+2:]
				continue
			}
			return ""
		default:
			return query
		}
	}
}

func handleSQL(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	args := req.GetArguments()
	query, ok := args["query"].(string)
	if !ok || query == "" {
		return mcplib.NewToolResultError("query is required"), nil
	}

	if err := validateReadOnlyQuery(query); err != nil {
		return mcplib.NewToolResultError(err.Error()), nil
	}

	db, err := store.OpenReadOnly(dbPath())
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("opening database: %v", err)), nil
	}
	defer db.Close()

	rows, err := db.Query(query)
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("query failed: %v", err)), nil
	}
	defer rows.Close()

	cols, _ := rows.Columns()
	var results []map[string]any
	for rows.Next() {
		values := make([]any, len(cols))
		ptrs := make([]any, len(cols))
		for i := range values {
			ptrs[i] = &values[i]
		}
		rows.Scan(ptrs...)
		row := make(map[string]any)
		for i, col := range cols {
			row[col] = values[i]
		}
		results = append(results, row)
	}

	data, _ := json.MarshalIndent(results, "", "  ")
	return mcplib.NewToolResultText(string(data)), nil
}

func handleContext(_ context.Context, _ mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	ctx := map[string]any{
		"api":         "orgo",
		"description": "Desktop infrastructure for AI agents. Create workspaces, provision virtual computers, and control them programmatically.",
		"archetype":   "generic",
		"tool_count":  33,
		// tool_surface tells agents which surface a capability lives on.
		"tool_surface": "MCP exposes typed endpoint tools plus a runtime mirror of user-facing CLI commands. Endpoint tools keep typed schemas; command-mirror tools shell out to the companion orgo-pp-cli binary.",
		"auth": map[string]any{
			"type": "bearer_token",
			"env_vars": []map[string]any{
				{
					"name":        "ORGO_API_KEY",
					"kind":        "per_call",
					"required":    true,
					"sensitive":   true,
					"description": "Set to your API credential.",
				},
			},
		},
		"resources": []map[string]any{
			{
				"name":        "computers",
				"description": "Provision and manage virtual computers",
				"endpoints":   []string{"create", "delete", "get"},
				"searchable":  true,
			},
			{
				"name":        "files",
				"description": "Upload and download files",
				"endpoints":   []string{"delete", "download", "export", "list", "upload"},
				"searchable":  true,
			},
			{
				"name":        "workspaces",
				"description": "Organize computers into named workspaces",
				"endpoints":   []string{"create", "delete", "get", "list"},
				"syncable":    true,
				"searchable":  true,
			},
		},
		"query_tips": []string{
			"Pagination uses cursor-based paging. Pass after parameter for subsequent pages.",
			"Control page size with the limit parameter (default 100).",
			"Use the sql tool for ad-hoc analysis on synced data. Run sync first to populate the local database.",
			"Use the search tool for full-text search across all synced resources. Faster than iterating list endpoints.",
			"Prefer sql/search over repeated API calls when the data is already synced.",
		},
		// Command-mirror capabilities are exposed through MCP by shelling out
		// to the companion CLI binary.
		"command_mirror_capabilities": []map[string]string{
			{"name": "Agent Action Replay", "command": "replay", "description": "Generate a self-contained static HTML timeline of every screenshot, click, bash, and exec your agent ran on a computer.", "rationale": "", "via": "mcp-command-mirror"},
			{"name": "Audit Trail", "command": "audit", "description": "Chronological table of every CLI-driven action against your computers in a time window, scoped by workspace,...", "rationale": "", "via": "mcp-command-mirror"},
			{"name": "Action Grep", "command": "grep", "description": "FTS5 search over historical bash commands, Python exec code, and click coordinates from the local actions store.", "rationale": "", "via": "mcp-command-mirror"},
			{"name": "Fleet Doctor", "command": "fleet", "description": "Cross-workspace health rollup: surfaces suspended (over-quota), errored, stuck-creating, and stuck-stopping...", "rationale": "", "via": "mcp-command-mirror"},
			{"name": "Idle Computers", "command": "idle", "description": "Sorts running computers by hours-since-last-CLI-action, surfacing burns that could be stopped.", "rationale": "", "via": "mcp-command-mirror"},
			{"name": "Oversized Computers", "command": "oversized", "description": "Flags computers with CPU >= 4 cores or RAM >= 16 GB whose last CLI-recorded action is older than the threshold and...", "rationale": "", "via": "mcp-command-mirror"},
			{"name": "Bulk Prune", "command": "prune", "description": "Cross-workspace status-filtered batch delete with dry-run by default.", "rationale": "", "via": "mcp-command-mirror"},
			{"name": "Cost Breakdown", "command": "cost", "description": "Reconstructs per-computer running-hours from local action timestamps + observed status transitions, multiplies by...", "rationale": "", "via": "mcp-command-mirror"},
		},
		"playbook": []map[string]string{
			{"topic": "Agent Action Replay", "insight": ""},
			{"topic": "Audit Trail", "insight": ""},
			{"topic": "Action Grep", "insight": ""},
			{"topic": "Fleet Doctor", "insight": ""},
			{"topic": "Idle Computers", "insight": ""},
			{"topic": "Oversized Computers", "insight": ""},
			{"topic": "Bulk Prune", "insight": ""},
			{"topic": "Cost Breakdown", "insight": ""},
		},
	}
	data, _ := json.MarshalIndent(ctx, "", "  ")
	return mcplib.NewToolResultText(string(data)), nil
}

// RegisterNovelFeatureTools is kept as a compatibility no-op for older MCP
// mains. New generated mains call RegisterTools only; RegisterTools now
// includes the runtime Cobra-tree mirror.
func RegisterNovelFeatureTools(s *server.MCPServer) {
	_ = s
}
