// Hand-authored: chrome transcendence command set. NOT generated by the
// Printing Press — the upstream OpenAPI spec describes the central Orgo REST
// API, but DOM-aware Chrome automation lives in a per-VM Node bridge that
// has no place in the spec. We re-implement orgo-chrome-mcp's 16-tool DOM
// surface as in-CLI subcommands so a single binary covers workspaces +
// computers + computer-use + browser-use, and the cobra-tree MCP walker
// auto-exposes every chrome subcommand as an MCP tool.
package cli

import (
	"context"
	"encoding/json"
	"fmt"
	"time"

	"github.com/nickvasilescu/orgo-pp-cli/internal/chrome"
	"github.com/nickvasilescu/orgo-pp-cli/internal/client"
	"github.com/spf13/cobra"
)

func newChromeCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "chrome",
		Short: "DOM-aware Chrome automation inside an Orgo VM (transcendence layer, not an API endpoint).",
		Long: `Drive Chrome inside an Orgo VM at the DOM level: read the accessibility
tree, find elements by intent, click by ref, type, evaluate JavaScript,
inspect console and network. Each command targets one computer by ID.

On first use against a VM, a small Node bridge (orgo-chrome-bridge.js) is
deployed into /tmp and started on 127.0.0.1:7331; subsequent calls reuse
it. The bridge is shipped embedded in this binary — no external download.

All chrome commands transparently inherit VM-direct routing flags
(--vm-from / --vm-url / --vm-token) because their underlying transport is
/computers/{id}/bash, which is already VM-bypassable.`,
		Example: `  # Cold-start: bridge auto-deploys on first call.
  orgo-pp-cli chrome navigate <computer-id> --url https://example.com

  # Read the page as an accessibility tree (cheap, fast).
  orgo-pp-cli chrome read-page <computer-id> --filter interactive

  # Find and click an element by intent.
  orgo-pp-cli chrome find <computer-id> --query "more information"
  orgo-pp-cli chrome click <computer-id> --ref ref_3

  # Save a real PNG to disk.
  orgo-pp-cli chrome screenshot <computer-id> --out /tmp/page.png

  # Use VM-direct routing for hot DOM loops.
  orgo-pp-cli chrome navigate <computer-id> --vm-from <computer-id> --url https://example.com`,
		Annotations: map[string]string{"mcp:read-only": "false"},
	}

	cmd.AddCommand(
		// Navigation (4)
		newChromeNavigateCmd(flags),
		newChromeTabsCmd(flags),
		newChromeNewTabCmd(flags),
		newChromeSwitchTabCmd(flags),
		// Reading (4)
		newChromeReadPageCmd(flags),
		newChromeFindCmd(flags),
		newChromePageTextCmd(flags),
		newChromeScreenshotCmd(flags),
		// Interaction (4)
		newChromeClickCmd(flags),
		newChromeTypeCmd(flags),
		newChromeFormInputCmd(flags),
		newChromeScrollCmd(flags),
		// Debug (3)
		newChromeEvaluateCmd(flags),
		newChromeConsoleCmd(flags),
		newChromeNetworkCmd(flags),
		// Window (1)
		newChromeResizeCmd(flags),
	)

	return cmd
}

// chromeManager wires the embedded BridgeManager to the existing
// client.Client's /computers/{id}/bash transport. VM-direct routing is
// transparent: when c.VMURL is set, c.Post rewrites the path to the per-VM
// agent and swaps Bearer auth — so chrome calls inherit the same hot-path
// latency win PR #483 delivered for bash/click/screenshot.
func chromeManager(c *client.Client) *chrome.Manager {
	return &chrome.Manager{
		Bash: func(ctx context.Context, computerID, command string) (string, error) {
			path := "/computers/" + computerID + "/bash"
			body := map[string]any{"command": command}
			data, _, err := c.Post(path, body)
			if err != nil {
				return "", err
			}
			return extractBashOutput(data), nil
		},
	}
}

// extractBashOutput normalizes the bash response shape across the central
// API and the per-VM agent. The central API returns
// {"output": "...", "exit_code": 0, ...}; the VM agent returns
// {"stdout": "...", "stderr": "...", ...}; some older paths returned
// {"result": "..."}.
//
// Special case: curl exit 52 ("empty reply from server") means the request
// reached the bridge but the bridge closed the connection without writing a
// body. This happens on a small set of bridge handlers (notably /switch_tab,
// which closes and reopens the CDP WebSocket mid-response). The action did
// succeed inside the VM; only the HTTP reply was lost. We synthesize a
// shaped success response so the chrome command surfaces a useful result
// instead of leaking the bash envelope. This mirrors how the upstream
// orgo-chrome-mcp would handle the same flow (its `curl -sf` would also
// fail; the TS code never validated the surrounding bash exit code).
func extractBashOutput(data json.RawMessage) string {
	var probe struct {
		Stdout   string `json:"stdout"`
		Output   string `json:"output"`
		Result   string `json:"result"`
		Action   string `json:"action"`
		ExitCode int    `json:"exit_code"`
	}
	_ = json.Unmarshal(data, &probe)
	switch {
	case probe.Stdout != "":
		return probe.Stdout
	case probe.Output != "":
		return probe.Output
	case probe.Result != "":
		return probe.Result
	}
	if probe.Action == "bash" && probe.ExitCode == 52 {
		return `{"success":true,"transport":"empty_body"}`
	}
	return string(data)
}

// runChromeCall is the shared command body for chrome subcommands that
// take a single positional <id>, build a JSON body from flags, hit one
// bridge endpoint, and print the raw response. Returns the parsed response
// so callers (e.g. screenshot --out) can post-process it.
func runChromeCall(cmd *cobra.Command, flags *rootFlags, args []string, method, path string, body any) (json.RawMessage, error) {
	if len(args) == 0 {
		return nil, cmd.Help()
	}
	c, err := flags.newClient()
	if err != nil {
		return nil, err
	}
	mgr := chromeManager(c)

	ctx, cancel := context.WithTimeout(cmd.Context(), 60*time.Second)
	defer cancel()

	resp, err := mgr.Call(ctx, args[0], method, path, body)
	if err != nil {
		return nil, fmt.Errorf("chrome %s %s: %w", method, path, err)
	}
	return resp, nil
}

// printChromeResp prints a bridge response in the right shape for the caller:
// JSON output for --json / --agent / pipes, pretty-printed JSON for terminals.
func printChromeResp(cmd *cobra.Command, flags *rootFlags, resp json.RawMessage) error {
	if len(resp) == 0 {
		return nil
	}
	if flags.asJSON || flags.agent || !isTerminal(cmd.OutOrStdout()) {
		fmt.Fprintln(cmd.OutOrStdout(), string(resp))
		return nil
	}
	var pretty json.RawMessage = resp
	var generic any
	if err := json.Unmarshal(resp, &generic); err == nil {
		if buf, err := json.MarshalIndent(generic, "", "  "); err == nil {
			pretty = buf
		}
	}
	fmt.Fprintln(cmd.OutOrStdout(), string(pretty))
	return nil
}
