// Copyright 2026 nickvasilescu. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newComputersDragCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "drag",
		Short: "Manage drag",
	}

	cmd.AddCommand(newComputersDragMouseCmd(flags))
	return cmd
}
