// Copyright 2026 nickvasilescu. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newComputersBashCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "bash",
		Short: "Manage bash",
	}

	cmd.AddCommand(newComputersBashExecuteCmd(flags))
	return cmd
}
