// Copyright 2026 nickvasilescu. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newComputersStreamCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "stream",
		Short: "Manage stream",
	}

	cmd.AddCommand(newComputersStreamGetStatusCmd(flags))
	cmd.AddCommand(newComputersStreamStartCmd(flags))
	cmd.AddCommand(newComputersStreamStopCmd(flags))
	return cmd
}
