// Copyright 2026 nickvasilescu. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newComputersVncPasswordCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "vnc-password",
		Short: "Manage vnc password",
	}

	cmd.AddCommand(newComputersVncPasswordGetCmd(flags))
	return cmd
}
