// Copyright 2026 nickvasilescu. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newComputersCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "computers",
		Short: "Provision and manage virtual computers",
	}

	cmd.AddCommand(newComputersCreateCmd(flags))
	cmd.AddCommand(newComputersDeleteCmd(flags))
	cmd.AddCommand(newComputersGetCmd(flags))
	cmd.AddCommand(newComputersAutoStopCmd(flags))
	cmd.AddCommand(newComputersBashCmd(flags))
	cmd.AddCommand(newComputersClickCmd(flags))
	cmd.AddCommand(newComputersCloneCmd(flags))
	cmd.AddCommand(newComputersDragCmd(flags))
	cmd.AddCommand(newComputersExecCmd(flags))
	cmd.AddCommand(newComputersKeyCmd(flags))
	cmd.AddCommand(newComputersMoveCmd(flags))
	cmd.AddCommand(newComputersResizeCmd(flags))
	cmd.AddCommand(newComputersRestartCmd(flags))
	cmd.AddCommand(newComputersScreenshotCmd(flags))
	cmd.AddCommand(newComputersScrollCmd(flags))
	cmd.AddCommand(newComputersStartCmd(flags))
	cmd.AddCommand(newComputersStopCmd(flags))
	cmd.AddCommand(newComputersStreamCmd(flags))
	cmd.AddCommand(newComputersTypeCmd(flags))
	cmd.AddCommand(newComputersVncPasswordCmd(flags))
	cmd.AddCommand(newComputersWaitCmd(flags))
	return cmd
}
