// Copyright 2026 nickvasilescu. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"
)

func newComputersCreateCmd(flags *rootFlags) *cobra.Command {
	var bodyAutoStopMinutes int
	var bodyCpu int
	var bodyDiskSizeGb int
	var bodyImage string
	var bodyName string
	var bodyOs string
	var bodyRam int
	var bodyResolution string
	var bodyWorkspaceId string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:         "create",
		Short:       "Creates a new virtual computer in a workspace. The computer starts automatically after creation.",
		Example:     "  orgo-pp-cli computers create --name example-resource",
		Annotations: map[string]string{"pp:endpoint": "computers.create", "pp:method": "POST", "pp:path": "/computers"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if !stdinBody {
				if !cmd.Flags().Changed("name") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "name")
				}
				if !cmd.Flags().Changed("workspace-id") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "workspace-id")
				}
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/computers"
			var body map[string]any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				body = map[string]any{}
				if bodyAutoStopMinutes != 0 {
					body["auto_stop_minutes"] = bodyAutoStopMinutes
				}
				if bodyCpu != 0 {
					body["cpu"] = bodyCpu
				}
				if bodyDiskSizeGb != 0 {
					body["disk_size_gb"] = bodyDiskSizeGb
				}
				if bodyImage != "" {
					body["image"] = bodyImage
				}
				if bodyName != "" {
					body["name"] = bodyName
				}
				if bodyOs != "" {
					body["os"] = bodyOs
				}
				if bodyRam != 0 {
					body["ram"] = bodyRam
				}
				if bodyResolution != "" {
					body["resolution"] = bodyResolution
				}
				if bodyWorkspaceId != "" {
					body["workspace_id"] = bodyWorkspaceId
				}
			}
			data, statusCode, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						return nil
					}
				} else {
					var wrapped struct {
						Data []map[string]any `json:"data"`
					}
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							return nil
						}
					}
				}
			}
			if flags.asJSON || !isTerminal(cmd.OutOrStdout()) {
				if flags.quiet {
					return nil
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				envelope := map[string]any{
					"action":   "post",
					"resource": "computers",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300,
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						envelope["data"] = parsed
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				return printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true)
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().IntVar(&bodyAutoStopMinutes, "auto-stop-minutes", 0, "Auto-stop after this many minutes of inactivity. Set to 0 to disable. Free tier locked to 15 minutes.")
	cmd.Flags().IntVar(&bodyCpu, "cpu", 1, "CPU cores. Capped by plan.")
	cmd.Flags().IntVar(&bodyDiskSizeGb, "disk-size-gb", 8, "Disk size in GB. Capped by plan.")
	cmd.Flags().StringVar(&bodyImage, "image", "", "Custom Docker image reference. Use with templates built via the SDK.")
	cmd.Flags().StringVar(&bodyName, "name", "", "Computer name")
	cmd.Flags().StringVar(&bodyOs, "os", "linux", "Operating system")
	cmd.Flags().IntVar(&bodyRam, "ram", 4, "RAM in GB. Capped by plan.")
	cmd.Flags().StringVar(&bodyResolution, "resolution", "1280x720x24", "Display resolution in WIDTHxHEIGHTxDEPTH format")
	cmd.Flags().StringVar(&bodyWorkspaceId, "workspace-id", "", "ID of the workspace to create the computer in")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
