// Copyright 2026 nickvasilescu. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newFilesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "files",
		Short: "Upload and download files",
	}

	cmd.AddCommand(newFilesDeleteCmd(flags))
	cmd.AddCommand(newFilesDownloadCmd(flags))
	cmd.AddCommand(newFilesExportCmd(flags))
	cmd.AddCommand(newFilesListCmd(flags))
	cmd.AddCommand(newFilesUploadCmd(flags))
	return cmd
}
