// Copyright 2026 nickvasilescu. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newFilesListCmd(flags *rootFlags) *cobra.Command {
	var flagProjectId string
	var flagDesktopId string

	cmd := &cobra.Command{
		Use:         "list",
		Short:       "Lists all files in a workspace, optionally filtered by computer.",
		Example:     "  orgo-pp-cli files list --project-id 550e8400-e29b-41d4-a716-446655440000",
		Annotations: map[string]string{"pp:endpoint": "files.list", "pp:method": "GET", "pp:path": "/files", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if !cmd.Flags().Changed("project-id") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "project-id")
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/files"
			params := map[string]string{}
			if flagProjectId != "" {
				params["projectId"] = fmt.Sprintf("%v", flagProjectId)
			}
			if flagDesktopId != "" {
				params["desktopId"] = fmt.Sprintf("%v", flagDesktopId)
			}
			data, err := c.GetWithHeaders(path, params, nil)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			if flags.asJSON || !isTerminal(cmd.OutOrStdout()) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				return printOutput(cmd.OutOrStdout(), filtered, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagProjectId, "project-id", "", "Workspace ID")
	cmd.Flags().StringVar(&flagDesktopId, "desktop-id", "", "Optional computer ID to filter by")

	return cmd
}
