// Copyright 2026 nickvasilescu. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"os"
	"strings"
	"text/tabwriter"
	"time"

	"github.com/nickvasilescu/orgo-pp-cli/internal/client"
	"github.com/nickvasilescu/orgo-pp-cli/internal/config"
	"github.com/spf13/cobra"
)

var version = "1.0.0"

type rootFlags struct {
	asJSON        bool
	compact       bool
	csv           bool
	plain         bool
	quiet         bool
	dryRun        bool
	noCache       bool
	noInput       bool
	idempotent    bool
	ignoreMissing bool
	yes           bool
	agent         bool
	selectFields  string
	configPath    string
	profileName   string
	deliverSpec   string
	timeout       time.Duration
	rateLimit     float64
	dataSource    string
	freshnessMeta any

	// VM-direct routing flags. When vmFrom is set, newClient() resolves the
	// computer's instance URL and vnc_password via a one-time central-API
	// `computers get` call and caches them in vmURL/vmToken for the session.
	// When vmURL/vmToken are set explicitly, no central call is made — useful
	// for agents born inside the VM with the values injected at boot.
	vmFrom  string
	vmURL   string
	vmToken string

	// deliverBuf captures command output when --deliver is set to a
	// non-stdout sink. Flushed to the sink after Execute returns.
	deliverBuf  *bytes.Buffer
	deliverSink DeliverSink
}

// RootCmd returns the Cobra command tree without executing it. The MCP server
// uses this to mirror every user-facing command as an agent tool.
func RootCmd() *cobra.Command {
	var flags rootFlags
	return newRootCmd(&flags)
}

// Execute runs the CLI in non-interactive mode: never prompts, all values via flags or stdin.
func Execute() error {
	var flags rootFlags
	rootCmd := newRootCmd(&flags)

	err := rootCmd.Execute()
	if err != nil && strings.Contains(err.Error(), "unknown flag") {
		msg := err.Error()
		// Extract the flag name from the error message (e.g., "unknown flag: --foob")
		if idx := strings.Index(msg, "unknown flag: "); idx >= 0 {
			flagStr := strings.TrimSpace(msg[idx+len("unknown flag: "):])
			if suggestion := suggestFlag(flagStr, rootCmd); suggestion != "" {
				return fmt.Errorf("%w\nhint: did you mean --%s?", err, suggestion)
			}
		}
	}
	if err == nil && flags.deliverBuf != nil {
		if derr := Deliver(flags.deliverSink, flags.deliverBuf.Bytes(), flags.compact); derr != nil {
			fmt.Fprintf(os.Stderr, "warning: deliver to %s:%s failed: %v\n", flags.deliverSink.Scheme, flags.deliverSink.Target, derr)
			return derr
		}
	}
	return err
}

func newRootCmd(flags *rootFlags) *cobra.Command {
	rootCmd := &cobra.Command{
		Use:   "orgo-pp-cli",
		Short: `Orgo CLI — The audit ledger Orgo doesn't otherwise have, plus every existing Orgo SDK feature in one Go binary.`,
		Long: `Orgo CLI — The audit ledger Orgo doesn't otherwise have, plus every existing Orgo SDK feature in one Go binary.

Highlights (not in the official API docs):
  • replay   Generate a self-contained static HTML timeline of every screenshot, click, bash, and exec your agent ran on a computer.
  • audit   Chronological table of every CLI-driven action against your computers in a time window, scoped by workspace, FTS-searchable.
  • grep   FTS5 search over historical bash commands, Python exec code, and click coordinates from the local actions store.
  • fleet   Cross-workspace health rollup: surfaces suspended (over-quota), errored, stuck-creating, and stuck-stopping computers, plus an API-key validity probe.
  • idle   Sorts running computers by hours-since-last-CLI-action, surfacing burns that could be stopped.
  • oversized   Flags computers with CPU >= 4 cores or RAM >= 16 GB whose last CLI-recorded action is older than the threshold and whose auto-stop is disabled.
  • prune   Cross-workspace status-filtered batch delete with dry-run by default.
  • cost   Reconstructs per-computer running-hours from local action timestamps + observed status transitions, multiplies by per-tier rate, sums by workspace. --forecast projects month-end burn.

Agent mode: add --agent to any command for JSON output + non-interactive mode.
Health check: run 'orgo-pp-cli doctor' to verify auth and connectivity.
See README.md or the bundled SKILL.md for recipes.`,
		SilenceUsage: true,
		Version:      version,
	}
	rootCmd.SetVersionTemplate("orgo-pp-cli {{ .Version }}\n")

	rootCmd.PersistentFlags().BoolVar(&flags.asJSON, "json", false, "Output as JSON")
	rootCmd.PersistentFlags().BoolVar(&flags.compact, "compact", false, "Return only key fields (id, name, status, timestamps) for minimal token usage")
	rootCmd.PersistentFlags().BoolVar(&flags.csv, "csv", false, "Output as CSV (table and array responses)")
	rootCmd.PersistentFlags().BoolVar(&flags.plain, "plain", false, "Output as plain tab-separated text")
	rootCmd.PersistentFlags().BoolVar(&flags.quiet, "quiet", false, "Bare output, one value per line")
	rootCmd.PersistentFlags().StringVar(&flags.configPath, "config", "", "Config file path")
	rootCmd.PersistentFlags().DurationVar(&flags.timeout, "timeout", 30*time.Second, "Request timeout")
	rootCmd.PersistentFlags().BoolVar(&flags.dryRun, "dry-run", false, "Show request without sending")
	rootCmd.PersistentFlags().BoolVar(&flags.noCache, "no-cache", false, "Bypass response cache")
	rootCmd.PersistentFlags().BoolVar(&flags.noInput, "no-input", false, "Disable all interactive prompts (for CI/agents)")
	rootCmd.PersistentFlags().BoolVar(&flags.idempotent, "idempotent", false, "Treat already-existing create results as a successful no-op")
	rootCmd.PersistentFlags().BoolVar(&flags.ignoreMissing, "ignore-missing", false, "Treat missing delete targets as a successful no-op")
	rootCmd.PersistentFlags().StringVar(&flags.selectFields, "select", "", "Comma-separated fields to include in output (e.g. --select id,name,status)")
	rootCmd.PersistentFlags().BoolVar(&flags.yes, "yes", false, "Skip confirmation prompts (for agents and scripts)")
	rootCmd.PersistentFlags().BoolVar(&noColor, "no-color", false, "Disable colored output")
	rootCmd.PersistentFlags().BoolVar(&humanFriendly, "human-friendly", false, "Enable colored output and rich formatting")
	rootCmd.PersistentFlags().BoolVar(&flags.agent, "agent", false, "Set all agent-friendly defaults (--json --compact --no-input --no-color --yes)")
	rootCmd.PersistentFlags().StringVar(&flags.dataSource, "data-source", "auto", "Data source for read commands: auto (live with local fallback), live (API only), local (synced data only)")
	rootCmd.PersistentFlags().StringVar(&flags.profileName, "profile", "", "Apply values from a saved profile (see 'orgo-pp-cli profile list')")
	rootCmd.PersistentFlags().StringVar(&flags.deliverSpec, "deliver", "", "Route output to a sink: stdout (default), file:<path>, webhook:<url>")
	rootCmd.PersistentFlags().Float64Var(&flags.rateLimit, "rate-limit", 0, "Max requests per second (0 to disable)")
	rootCmd.PersistentFlags().StringVar(&flags.vmFrom, "vm-from", "", "Route computer-use endpoints (bash/click/type/key/scroll/drag/exec/screenshot) directly to the named computer's VM agent; resolves URL + token via a one-time `computers get` call.")
	rootCmd.PersistentFlags().StringVar(&flags.vmURL, "vm-url", "", "Per-VM agent URL (e.g. http://1.2.3.4:36100). When set with --vm-token, bypasses --vm-from's central API lookup.")
	rootCmd.PersistentFlags().StringVar(&flags.vmToken, "vm-token", "", "Per-VM bearer token (the computer's vnc_password). Required with --vm-url; falls back to $ORGO_VM_TOKEN.")

	rootCmd.PersistentPreRunE = func(cmd *cobra.Command, args []string) error {
		if flags.deliverSpec != "" {
			sink, err := ParseDeliverSink(flags.deliverSpec)
			if err != nil {
				return err
			}
			flags.deliverSink = sink
			if sink.Scheme != "stdout" && sink.Scheme != "" {
				flags.deliverBuf = &bytes.Buffer{}
				cmd.SetOut(io.MultiWriter(os.Stdout, flags.deliverBuf))
			}
		}
		if flags.profileName != "" {
			profile, err := GetProfile(flags.profileName)
			if err != nil {
				return err
			}
			if profile == nil {
				available := ListProfileNames()
				if len(available) == 0 {
					return fmt.Errorf("profile %q not found (no profiles saved yet; run '%s profile save <name> --<flag> <value>')", flags.profileName, cmd.Root().Name())
				}
				return fmt.Errorf("profile %q not found; available: %s", flags.profileName, strings.Join(available, ", "))
			}
			if err := ApplyProfileToFlags(cmd, profile); err != nil {
				return err
			}
		}
		if flags.agent {
			if !cmd.Flags().Changed("json") {
				flags.asJSON = true
			}
			if !cmd.Flags().Changed("compact") {
				flags.compact = true
			}
			if !cmd.Flags().Changed("no-input") {
				flags.noInput = true
			}
			if !cmd.Flags().Changed("yes") {
				flags.yes = true
			}
			if !cmd.Flags().Changed("no-color") {
				noColor = true
			}
		}
		switch flags.dataSource {
		case "auto", "live", "local":
			// valid
		default:
			return fmt.Errorf("invalid --data-source value %q: must be auto, live, or local", flags.dataSource)
		}
		return nil
	}
	rootCmd.AddCommand(newComputersCmd(flags))
	rootCmd.AddCommand(newFilesCmd(flags))
	rootCmd.AddCommand(newWorkspacesCmd(flags))
	rootCmd.AddCommand(newDoctorCmd(flags))
	rootCmd.AddCommand(newAuthCmd(flags))
	rootCmd.AddCommand(newAgentContextCmd(rootCmd))
	rootCmd.AddCommand(newProfileCmd(flags))
	rootCmd.AddCommand(newFeedbackCmd(flags))
	rootCmd.AddCommand(newWhichCmd(flags))
	rootCmd.AddCommand(newExportCmd(flags))
	rootCmd.AddCommand(newImportCmd(flags))
	rootCmd.AddCommand(newSearchCmd(flags))
	rootCmd.AddCommand(newSyncCmd(flags))
	rootCmd.AddCommand(newWorkflowCmd(flags))
	rootCmd.AddCommand(newVersionCliCmd())

	// Hand-authored novel commands (Phase 3 transcendence layer). These
	// expose the local actions ledger and fleet rollups that no live
	// API call can produce on its own.
	rootCmd.AddCommand(newAuditCmd(flags))
	rootCmd.AddCommand(newGrepCmd(flags))
	rootCmd.AddCommand(newReplayCmd(flags))
	rootCmd.AddCommand(newIdleCmd(flags))
	rootCmd.AddCommand(newOversizedCmd(flags))
	rootCmd.AddCommand(newPruneCmd(flags))
	rootCmd.AddCommand(newCostCmd(flags))
	rootCmd.AddCommand(newFleetCmd(flags))

	return rootCmd
}

func ExitCode(err error) int {
	var codeErr *cliError
	if As(err, &codeErr) {
		return codeErr.code
	}
	return 1
}

func (f *rootFlags) newClient() (*client.Client, error) {
	cfg, err := config.Load(f.configPath)
	if err != nil {
		return nil, configErr(err)
	}
	c := client.New(cfg, f.timeout, f.rateLimit)
	c.DryRun = f.dryRun
	c.NoCache = f.noCache

	// VM-direct routing. Resolution order:
	//   1. --vm-url + --vm-token explicit (skip central API entirely)
	//   2. $ORGO_VM_URL + $ORGO_VM_TOKEN env (for in-VM agents)
	//   3. --vm-from <computer-id> (one-time central GET to resolve url + vnc_password)
	vmURL := f.vmURL
	vmToken := f.vmToken
	if vmURL == "" {
		vmURL = os.Getenv("ORGO_VM_URL")
	}
	if vmToken == "" {
		vmToken = os.Getenv("ORGO_VM_TOKEN")
	}
	switch {
	case vmURL != "":
		if vmToken == "" {
			return nil, usageErr(fmt.Errorf("--vm-url requires --vm-token (or $ORGO_VM_TOKEN)"))
		}
		c.VMURL = vmURL
		c.VMToken = vmToken
	case f.vmFrom != "":
		resolvedURL, resolvedToken, rerr := resolveVMTarget(c, f.vmFrom)
		if rerr != nil {
			return nil, fmt.Errorf("--vm-from %s: %w", f.vmFrom, rerr)
		}
		c.VMURL = resolvedURL
		c.VMToken = resolvedToken
		// Cache back into rootFlags so subsequent newClient() calls in the
		// same invocation skip the central lookup. Most commands call
		// newClient() once, but commands like 'audit'/'replay' do multiple.
		f.vmURL = resolvedURL
		f.vmToken = resolvedToken
	}
	return c, nil
}

// resolveVMTarget performs a one-time central-API GET /computers/<id> to
// extract the computer's instance URL and vnc_password. Used by --vm-from
// to avoid making the user paste both manually.
func resolveVMTarget(c *client.Client, computerID string) (string, string, error) {
	data, err := c.Get("/computers/"+computerID, nil)
	if err != nil {
		return "", "", err
	}
	var d struct {
		URL         string `json:"url"`
		VNCPassword string `json:"vnc_password"`
	}
	if err := json.Unmarshal(data, &d); err != nil {
		return "", "", fmt.Errorf("parsing computers/%s response: %w", computerID, err)
	}
	if d.URL == "" {
		return "", "", fmt.Errorf("computer %s has no `url` field; not started?", computerID)
	}
	if d.VNCPassword == "" {
		return "", "", fmt.Errorf("computer %s has no `vnc_password` field; cannot authenticate to VM agent", computerID)
	}
	return d.URL, d.VNCPassword, nil
}

func (f *rootFlags) printJSON(w *cobra.Command, v any) error {
	enc := json.NewEncoder(w.OutOrStdout())
	enc.SetIndent("", "  ")
	return enc.Encode(v)
}

func (f *rootFlags) printTable(w *cobra.Command, headers []string, rows [][]string) error {
	if f.asJSON {
		return fmt.Errorf("use printJSON for JSON output")
	}
	tw := tabwriter.NewWriter(w.OutOrStdout(), 2, 4, 2, ' ', 0)
	header := ""
	for i, h := range headers {
		if i > 0 {
			header += "\t"
		}
		header += h
	}
	fmt.Fprintln(tw, header)
	for _, row := range rows {
		line := ""
		for i, cell := range row {
			if i > 0 {
				line += "\t"
			}
			line += cell
		}
		fmt.Fprintln(tw, line)
	}
	return tw.Flush()
}

func newVersionCliCmd() *cobra.Command {
	return &cobra.Command{
		Use:   "version",
		Short: "Print version",
		Run: func(cmd *cobra.Command, args []string) {
			fmt.Printf("orgo-pp-cli %s\n", version)
		},
	}
}
