// Copyright 2026 nickvasilescu. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

// Package store provides local SQLite persistence for orgo-pp-cli.
// Uses modernc.org/sqlite (pure Go, no CGO) for zero-dependency cross-compilation.
// FTS5 full-text search indexes are created for searchable content.
package store

import (
	"context"
	"database/sql"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"sync"
	"time"

	_ "modernc.org/sqlite"
)

var uuidPattern = regexp.MustCompile(`^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$`)

// IsUUID returns true if the input looks like a UUID.
func IsUUID(s string) bool {
	return uuidPattern.MatchString(s)
}

// StoreSchemaVersion is the on-disk schema version this binary understands.
// It is stamped into SQLite's PRAGMA user_version on fresh databases and
// checked on every open. Bump this whenever a migration changes table
// shape — adding columns, dropping indexes, changing FTS5 tokenizers —
// so an older binary refuses to open a newer database rather than silently
// producing wrong results against a schema it cannot read.
const StoreSchemaVersion = 1

type Store struct {
	db *sql.DB
	// writeMu serializes all DB writes. Read paths bypass the lock and run
	// concurrently against WAL. Resource-level concurrency in sync.go.tmpl
	// is 1 (one goroutine per resource via len(resources)-sized work channel)
	// — read-then-write sequences (e.g., GetSyncCursor → SaveSyncState) are
	// race-free by construction within a resource.
	writeMu sync.Mutex
	path    string
}

// Open opens or creates the SQLite store at dbPath using the background
// context. Prefer OpenWithContext from a Cobra command so SIGINT during
// a slow migration interrupts the open instead of stranding the caller.
func Open(dbPath string) (*Store, error) {
	return OpenWithContext(context.Background(), dbPath)
}

// OpenReadOnly opens an existing SQLite store at dbPath in read-only mode.
// mode=ro rejects direct and CTE-wrapped writes (INSERT, UPDATE, DELETE,
// REPLACE, "WITH x AS (...) INSERT ...") at the driver level. Skips
// MkdirAll and migrate; the file is expected to exist.
//
// The file: URI prefix is load-bearing: modernc.org/sqlite only honors
// SQLite's URI query parameters (mode, cache, etc.) when the DSN starts
// with "file:". Without the prefix, "?mode=ro" is silently dropped and
// the connection opens read-write. Underscore-prefixed driver pragmas
// (_journal_mode, _busy_timeout, etc.) work either way; they're parsed
// out of the DSN by the driver before sqlite3_open_v2.
func OpenReadOnly(dbPath string) (*Store, error) {
	db, err := sql.Open("sqlite", "file:"+dbPath+"?mode=ro&_journal_mode=WAL&_busy_timeout=5000&_foreign_keys=ON&_temp_store=MEMORY&_mmap_size=268435456")
	if err != nil {
		return nil, fmt.Errorf("opening database (read-only): %w", err)
	}
	db.SetMaxOpenConns(2)
	return &Store{db: db, path: dbPath}, nil
}

// OpenWithContext opens or creates the SQLite store at dbPath. The
// context is honored by the migration path: cancellation interrupts the
// retry-on-SQLITE_BUSY loop and propagates ctx.Err() back to the caller
// instead of waiting out the full migrationLockTimeout.
func OpenWithContext(ctx context.Context, dbPath string) (*Store, error) {
	if err := os.MkdirAll(filepath.Dir(dbPath), 0o755); err != nil {
		return nil, fmt.Errorf("creating db directory: %w", err)
	}

	db, err := sql.Open("sqlite", dbPath+"?_journal_mode=WAL&_synchronous=NORMAL&_busy_timeout=5000&_foreign_keys=ON&_temp_store=MEMORY&_mmap_size=268435456")
	if err != nil {
		return nil, fmt.Errorf("opening database: %w", err)
	}

	// WAL mode + 2 connections allows one read cursor open while a second
	// query executes (e.g., analytics commands calling helpers during row
	// iteration). Writes are still serialized by SQLite's WAL lock.
	db.SetMaxOpenConns(2)

	s := &Store{db: db, path: dbPath}
	if err := s.migrate(ctx); err != nil {
		db.Close()
		return nil, fmt.Errorf("running migrations: %w", err)
	}

	return s, nil
}

func (s *Store) Close() error {
	return s.db.Close()
}

// Path returns the on-disk path of the backing SQLite file.
func (s *Store) Path() string {
	return s.path
}

// DB exposes the underlying *sql.DB for callers that need to run ad-hoc
// queries (e.g., doctor's cache inspection, share snapshot import).
// Callers must not call Close on the returned handle.
func (s *Store) DB() *sql.DB {
	return s.db
}

// SchemaVersion reads PRAGMA user_version, which is stamped by migrate().
// A zero value means the database predates the schema-version gate — not
// a bug, but the caller may want to warn.
func (s *Store) SchemaVersion() (int, error) {
	var v int
	if err := s.db.QueryRow(`PRAGMA user_version`).Scan(&v); err != nil {
		return 0, fmt.Errorf("read user_version: %w", err)
	}
	return v, nil
}

// ensureColumn adds a column to an existing table if it isn't already
// present. It is the upgrade-path safety valve for schema additions:
// CREATE TABLE IF NOT EXISTS is a no-op when the table already exists, so
// columns added by newer binaries (e.g. parent_id from the dependent-
// resources work) never land on databases created by older binaries —
// which then trip "no such column" when a follow-on CREATE INDEX runs.
//
// Skips silently if the table doesn't yet exist (fresh install — the
// CREATE TABLE migration will create it with the column already declared)
// or if the column already exists. Runs on the pinned migration
// connection so it sees the writes performed by the in-flight BEGIN
// IMMEDIATE transaction; using s.db here would route through the pool
// and BUSY against the holding writer under concurrent migrators.
func (s *Store) ensureColumn(ctx context.Context, conn *sql.Conn, table, column, decl string) error {
	var name string
	err := conn.QueryRowContext(ctx,
		`SELECT name FROM sqlite_master WHERE type='table' AND name=?`, table,
	).Scan(&name)
	if err == sql.ErrNoRows {
		return nil
	}
	if err != nil {
		return fmt.Errorf("checking table %s: %w", table, err)
	}

	rows, err := conn.QueryContext(ctx, fmt.Sprintf(`PRAGMA table_info("%s")`, table))
	if err != nil {
		return fmt.Errorf("table_info %s: %w", table, err)
	}
	defer rows.Close()
	for rows.Next() {
		var cid int
		var n, typ string
		var notnull, pk int
		var dflt sql.NullString
		if err := rows.Scan(&cid, &n, &typ, &notnull, &dflt, &pk); err != nil {
			return fmt.Errorf("scan table_info %s: %w", table, err)
		}
		if n == column {
			return nil
		}
	}
	if err := rows.Err(); err != nil {
		return fmt.Errorf("iterating table_info %s: %w", table, err)
	}

	if _, err := conn.ExecContext(ctx, fmt.Sprintf(`ALTER TABLE "%s" ADD COLUMN "%s" %s`, table, column, decl)); err != nil {
		// A concurrent Open() may have added the column between our
		// PRAGMA check and this ALTER. SQLite returns SQLITE_ERROR with
		// "duplicate column name", which busy_timeout does not retry.
		// The DB is now in the desired state regardless of who won.
		if strings.Contains(err.Error(), "duplicate column name") {
			return nil
		}
		return fmt.Errorf("add column %s.%s: %w", table, column, err)
	}
	return nil
}

// backfillColumns adds columns that newer binaries declare but that
// pre-existing databases (created before those columns were added) lack.
// Must run before the migrations slice so that subsequent CREATE INDEX
// statements referencing the column can succeed against the upgraded
// table. Idempotent: safe to call on fresh DBs (table-not-found short-
// circuit) and on already-current DBs (column-exists short-circuit).
//
// Table names are emitted bare (no safeName) — ensureColumn double-quotes
// them at SQL emit time and uses parameter binding for the sqlite_master
// lookup, so the values flow as Go string literals first and SQL
// identifiers second. Wrapping with safeName here would embed literal
// double-quote characters into the Go string and break compilation for
// any spec whose dependent-resource snake_cased name is a SQL reserved
// word.
func (s *Store) backfillColumns(ctx context.Context, conn *sql.Conn) error {
	for _, c := range []struct{ table, column, decl string }{
		{table: "computers", column: "connection_url", decl: "TEXT"},
		{table: "computers", column: "cpu", decl: "INTEGER"},
		{table: "computers", column: "created_at", decl: "DATETIME"},
		{table: "computers", column: "disk_size_gb", decl: "INTEGER"},
		{table: "computers", column: "fly_instance_id", decl: "TEXT"},
		{table: "computers", column: "hostname", decl: "TEXT"},
		{table: "computers", column: "name", decl: "TEXT"},
		{table: "computers", column: "os", decl: "TEXT"},
		{table: "computers", column: "project_name", decl: "TEXT"},
		{table: "computers", column: "ram", decl: "INTEGER"},
		{table: "computers", column: "status", decl: "TEXT"},
		{table: "computers", column: "url", decl: "TEXT"},
		{table: "computers", column: "vnc_password", decl: "TEXT"},
		{table: "auto_stop", column: "computers_id", decl: "TEXT"},
		{table: "bash", column: "computers_id", decl: "TEXT"},
		{table: "click", column: "computers_id", decl: "TEXT"},
		{table: "clone", column: "computers_id", decl: "TEXT"},
		{table: "drag", column: "computers_id", decl: "TEXT"},
		{table: "exec", column: "computers_id", decl: "TEXT"},
		{table: "key", column: "computers_id", decl: "TEXT"},
		{table: "move", column: "computers_id", decl: "TEXT"},
		{table: "resize", column: "computers_id", decl: "TEXT"},
		{table: "restart", column: "computers_id", decl: "TEXT"},
		{table: "screenshot", column: "computers_id", decl: "TEXT"},
		{table: "scroll", column: "computers_id", decl: "TEXT"},
		{table: "start", column: "computers_id", decl: "TEXT"},
		{table: "stop", column: "computers_id", decl: "TEXT"},
		{table: "stream", column: "computers_id", decl: "TEXT"},
		{table: "type", column: "computers_id", decl: "TEXT"},
		{table: "vnc_password", column: "computers_id", decl: "TEXT"},
		{table: "wait", column: "computers_id", decl: "TEXT"},
		{table: "files", column: "url", decl: "TEXT"},
		{table: "workspaces", column: "created_at", decl: "DATETIME"},
		{table: "workspaces", column: "icon_url", decl: "TEXT"},
		{table: "workspaces", column: "name", decl: "TEXT"},
		{table: "workspaces", column: "status", decl: "TEXT"},
		{table: "workspaces", column: "updated_at", decl: "DATETIME"},
		{table: "workspaces", column: "user_id", decl: "TEXT"},
		{table: "sync_state", column: "last_cursor", decl: "TEXT"},
		{table: "sync_state", column: "last_synced_at", decl: "DATETIME"},
		{table: "sync_state", column: "total_count", decl: "INTEGER DEFAULT 0"},
	} {
		if err := s.ensureColumn(ctx, conn, c.table, c.column, c.decl); err != nil {
			return err
		}
	}
	return nil
}

func (s *Store) migrate(ctx context.Context) error {
	conn, err := s.db.Conn(ctx)
	if err != nil {
		return fmt.Errorf("acquiring migration connection: %w", err)
	}
	defer conn.Close()

	// Read user_version before the migration lock so an old binary
	// opening a newer-schema DB rejects immediately. WAL readers don't
	// normally block on writers, but the fresh-DB WAL-init race can BUSY
	// a SELECT — share the lock's deadline so total budget stays bounded.
	deadline := time.Now().Add(migrationLockTimeout)
	var current int
	if err := retryOnBusy(ctx, deadline, "reading schema version", func() error {
		return conn.QueryRowContext(ctx, `PRAGMA user_version`).Scan(&current)
	}); err != nil {
		return err
	}
	if current > StoreSchemaVersion {
		return fmt.Errorf("database schema version %d is newer than supported version %d; upgrade the CLI binary or open an older database", current, StoreSchemaVersion)
	}

	migrations := []string{
		`CREATE TABLE IF NOT EXISTS resources (
			id TEXT PRIMARY KEY,
			resource_type TEXT NOT NULL,
			data JSON NOT NULL,
			synced_at DATETIME DEFAULT CURRENT_TIMESTAMP,
			updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
		)`,
		`CREATE INDEX IF NOT EXISTS idx_resources_type ON resources(resource_type)`,
		`CREATE INDEX IF NOT EXISTS idx_resources_synced ON resources(synced_at)`,
		`CREATE TABLE IF NOT EXISTS sync_state (
			resource_type TEXT PRIMARY KEY,
			last_cursor TEXT,
			last_synced_at DATETIME,
			total_count INTEGER DEFAULT 0
		)`,
		`CREATE VIRTUAL TABLE IF NOT EXISTS resources_fts USING fts5(
			id, resource_type, content, tokenize='porter unicode61'
		)`,
		`CREATE TABLE IF NOT EXISTS computers (
			id TEXT PRIMARY KEY,
			data JSON NOT NULL,
			synced_at DATETIME DEFAULT CURRENT_TIMESTAMP,
			connection_url TEXT,
			cpu INTEGER,
			created_at DATETIME,
			disk_size_gb INTEGER,
			fly_instance_id TEXT,
			hostname TEXT,
			name TEXT,
			os TEXT,
			project_name TEXT,
			ram INTEGER,
			status TEXT,
			url TEXT,
			vnc_password TEXT
		)`,
		`CREATE INDEX IF NOT EXISTS idx_computers_fly_instance_id ON computers(fly_instance_id)`,
		`CREATE INDEX IF NOT EXISTS idx_computers_created_at ON computers(created_at)`,
		`CREATE TABLE IF NOT EXISTS auto_stop (
			id TEXT PRIMARY KEY,
			computers_id TEXT NOT NULL,
			data JSON NOT NULL,
			synced_at DATETIME DEFAULT CURRENT_TIMESTAMP
		)`,
		`CREATE INDEX IF NOT EXISTS idx_auto_stop_computers_id ON auto_stop(computers_id)`,
		`CREATE TABLE IF NOT EXISTS bash (
			id TEXT PRIMARY KEY,
			computers_id TEXT NOT NULL,
			data JSON NOT NULL,
			synced_at DATETIME DEFAULT CURRENT_TIMESTAMP
		)`,
		`CREATE INDEX IF NOT EXISTS idx_bash_computers_id ON bash(computers_id)`,
		`CREATE TABLE IF NOT EXISTS click (
			id TEXT PRIMARY KEY,
			computers_id TEXT NOT NULL,
			data JSON NOT NULL,
			synced_at DATETIME DEFAULT CURRENT_TIMESTAMP
		)`,
		`CREATE INDEX IF NOT EXISTS idx_click_computers_id ON click(computers_id)`,
		`CREATE TABLE IF NOT EXISTS clone (
			id TEXT PRIMARY KEY,
			computers_id TEXT NOT NULL,
			data JSON NOT NULL,
			synced_at DATETIME DEFAULT CURRENT_TIMESTAMP
		)`,
		`CREATE INDEX IF NOT EXISTS idx_clone_computers_id ON clone(computers_id)`,
		`CREATE TABLE IF NOT EXISTS drag (
			id TEXT PRIMARY KEY,
			computers_id TEXT NOT NULL,
			data JSON NOT NULL,
			synced_at DATETIME DEFAULT CURRENT_TIMESTAMP
		)`,
		`CREATE INDEX IF NOT EXISTS idx_drag_computers_id ON drag(computers_id)`,
		`CREATE TABLE IF NOT EXISTS exec (
			id TEXT PRIMARY KEY,
			computers_id TEXT NOT NULL,
			data JSON NOT NULL,
			synced_at DATETIME DEFAULT CURRENT_TIMESTAMP
		)`,
		`CREATE INDEX IF NOT EXISTS idx_exec_computers_id ON exec(computers_id)`,
		`CREATE TABLE IF NOT EXISTS "key" (
			id TEXT PRIMARY KEY,
			computers_id TEXT NOT NULL,
			data JSON NOT NULL,
			synced_at DATETIME DEFAULT CURRENT_TIMESTAMP
		)`,
		`CREATE INDEX IF NOT EXISTS idx_key_computers_id ON "key"(computers_id)`,
		`CREATE TABLE IF NOT EXISTS move (
			id TEXT PRIMARY KEY,
			computers_id TEXT NOT NULL,
			data JSON NOT NULL,
			synced_at DATETIME DEFAULT CURRENT_TIMESTAMP
		)`,
		`CREATE INDEX IF NOT EXISTS idx_move_computers_id ON move(computers_id)`,
		`CREATE TABLE IF NOT EXISTS resize (
			id TEXT PRIMARY KEY,
			computers_id TEXT NOT NULL,
			data JSON NOT NULL,
			synced_at DATETIME DEFAULT CURRENT_TIMESTAMP
		)`,
		`CREATE INDEX IF NOT EXISTS idx_resize_computers_id ON resize(computers_id)`,
		`CREATE TABLE IF NOT EXISTS restart (
			id TEXT PRIMARY KEY,
			computers_id TEXT NOT NULL,
			data JSON NOT NULL,
			synced_at DATETIME DEFAULT CURRENT_TIMESTAMP
		)`,
		`CREATE INDEX IF NOT EXISTS idx_restart_computers_id ON restart(computers_id)`,
		`CREATE TABLE IF NOT EXISTS screenshot (
			id TEXT PRIMARY KEY,
			computers_id TEXT NOT NULL,
			data JSON NOT NULL,
			synced_at DATETIME DEFAULT CURRENT_TIMESTAMP
		)`,
		`CREATE INDEX IF NOT EXISTS idx_screenshot_computers_id ON screenshot(computers_id)`,
		`CREATE TABLE IF NOT EXISTS scroll (
			id TEXT PRIMARY KEY,
			computers_id TEXT NOT NULL,
			data JSON NOT NULL,
			synced_at DATETIME DEFAULT CURRENT_TIMESTAMP
		)`,
		`CREATE INDEX IF NOT EXISTS idx_scroll_computers_id ON scroll(computers_id)`,
		`CREATE TABLE IF NOT EXISTS start (
			id TEXT PRIMARY KEY,
			computers_id TEXT NOT NULL,
			data JSON NOT NULL,
			synced_at DATETIME DEFAULT CURRENT_TIMESTAMP
		)`,
		`CREATE INDEX IF NOT EXISTS idx_start_computers_id ON start(computers_id)`,
		`CREATE TABLE IF NOT EXISTS stop (
			id TEXT PRIMARY KEY,
			computers_id TEXT NOT NULL,
			data JSON NOT NULL,
			synced_at DATETIME DEFAULT CURRENT_TIMESTAMP
		)`,
		`CREATE INDEX IF NOT EXISTS idx_stop_computers_id ON stop(computers_id)`,
		`CREATE TABLE IF NOT EXISTS stream (
			id TEXT PRIMARY KEY,
			computers_id TEXT NOT NULL,
			data JSON NOT NULL,
			synced_at DATETIME DEFAULT CURRENT_TIMESTAMP
		)`,
		`CREATE INDEX IF NOT EXISTS idx_stream_computers_id ON stream(computers_id)`,
		`CREATE TABLE IF NOT EXISTS type (
			id TEXT PRIMARY KEY,
			computers_id TEXT NOT NULL,
			data JSON NOT NULL,
			synced_at DATETIME DEFAULT CURRENT_TIMESTAMP
		)`,
		`CREATE INDEX IF NOT EXISTS idx_type_computers_id ON type(computers_id)`,
		`CREATE TABLE IF NOT EXISTS vnc_password (
			id TEXT PRIMARY KEY,
			computers_id TEXT NOT NULL,
			data JSON NOT NULL,
			synced_at DATETIME DEFAULT CURRENT_TIMESTAMP
		)`,
		`CREATE INDEX IF NOT EXISTS idx_vnc_password_computers_id ON vnc_password(computers_id)`,
		`CREATE TABLE IF NOT EXISTS wait (
			id TEXT PRIMARY KEY,
			computers_id TEXT NOT NULL,
			data JSON NOT NULL,
			synced_at DATETIME DEFAULT CURRENT_TIMESTAMP
		)`,
		`CREATE INDEX IF NOT EXISTS idx_wait_computers_id ON wait(computers_id)`,
		`CREATE TABLE IF NOT EXISTS files (
			id TEXT PRIMARY KEY,
			data JSON NOT NULL,
			synced_at DATETIME DEFAULT CURRENT_TIMESTAMP,
			url TEXT
		)`,
		`CREATE TABLE IF NOT EXISTS workspaces (
			id TEXT PRIMARY KEY,
			data JSON NOT NULL,
			synced_at DATETIME DEFAULT CURRENT_TIMESTAMP,
			created_at DATETIME,
			icon_url TEXT,
			name TEXT,
			status TEXT,
			updated_at DATETIME,
			user_id TEXT
		)`,
		`CREATE INDEX IF NOT EXISTS idx_workspaces_user_id ON workspaces(user_id)`,
		`CREATE INDEX IF NOT EXISTS idx_workspaces_created_at ON workspaces(created_at)`,
		`CREATE INDEX IF NOT EXISTS idx_workspaces_updated_at ON workspaces(updated_at)`,
	}

	// Run every migration — including the column backfill and the
	// schema-version stamp — inside a single BEGIN IMMEDIATE transaction
	// pinned to one connection. IMMEDIATE acquires SQLite's RESERVED lock
	// at BEGIN time so concurrent migrators serialize on it instead of
	// racing per-statement and tripping SQLITE_BUSY despite busy_timeout.
	// modernc.org/sqlite's busy_timeout does not always cover write-write
	// contention at BEGIN/COMMIT time, so we retry both explicitly on
	// SQLITE_BUSY for up to migrationLockTimeout.
	return withMigrationLock(ctx, conn, deadline, func() error {
		// Re-read user_version inside the lock. This is load-bearing,
		// not paranoid: between the pre-lock read above and our
		// successful BEGIN IMMEDIATE, a newer-binary peer may have
		// committed a higher version stamp. Without this re-read, an
		// older binary (smaller StoreSchemaVersion) would proceed to
		// stamp its own lower version at the end of the closure,
		// silently downgrading user_version on a schema that's already
		// at the newer level. Future maintainers: leave this read in.
		var current int
		if err := conn.QueryRowContext(ctx, `PRAGMA user_version`).Scan(&current); err != nil {
			return fmt.Errorf("reading schema version: %w", err)
		}
		if current > StoreSchemaVersion {
			return fmt.Errorf("database schema version %d is newer than supported version %d; upgrade the CLI binary or open an older database", current, StoreSchemaVersion)
		}

		if err := s.backfillColumns(ctx, conn); err != nil {
			return fmt.Errorf("backfilling columns: %w", err)
		}
		for _, m := range migrations {
			if _, err := conn.ExecContext(ctx, m); err != nil {
				return fmt.Errorf("migration failed: %w", err)
			}
		}
		// Stamp the schema version. On a fresh DB this writes 1; on an
		// already-stamped DB this is a no-op write of the same value.
		// An older DB with user_version = 0 and pre-existing tables
		// gets stamped here without any data rewrites because the
		// migrations above are idempotent via CREATE TABLE IF NOT EXISTS.
		if _, err := conn.ExecContext(ctx, fmt.Sprintf(`PRAGMA user_version = %d`, StoreSchemaVersion)); err != nil {
			return fmt.Errorf("stamp user_version: %w", err)
		}
		return nil
	})
}

const (
	migrationLockTimeout    = 30 * time.Second
	migrationLockBackoffMin = 5 * time.Millisecond
	migrationLockBackoffMax = 100 * time.Millisecond
)

// withMigrationLock runs fn inside a BEGIN IMMEDIATE / COMMIT pair on
// conn, retrying both BEGIN and COMMIT on SQLITE_BUSY against the
// caller-provided deadline. Sharing the deadline with the pre-lock
// version read keeps total Open() latency bounded by a single budget.
// The real upper bound is deadline + one trailing backoff interval
// (≤100ms) + the driver's busy_timeout for the in-flight Exec, since
// the deadline is checked after each failed attempt rather than as a
// hard wall-clock cutoff. fn must use conn (not s.db) so its writes
// participate in the held transaction.
func withMigrationLock(ctx context.Context, conn *sql.Conn, deadline time.Time, fn func() error) error {
	if err := execWithBusyRetry(ctx, conn, "BEGIN IMMEDIATE", "begin migration transaction", deadline); err != nil {
		return err
	}
	committed := false
	defer func() {
		if committed {
			return
		}
		// ROLLBACK uses context.Background() so caller-context cancellation
		// can't strand the connection in an open transaction. A failed
		// rollback is rare on local SQLite (broken file handle, fatal
		// driver error) but worth surfacing — silent swallow leaves a
		// pinned connection returned to the pool with state that will
		// confuse later queries.
		if _, rerr := conn.ExecContext(context.Background(), "ROLLBACK"); rerr != nil {
			fmt.Fprintf(os.Stderr, "warning: store migration rollback failed: %v\n", rerr)
		}
	}()

	if err := fn(); err != nil {
		return err
	}

	if err := execWithBusyRetry(ctx, conn, "COMMIT", "commit migration transaction", deadline); err != nil {
		return err
	}
	committed = true
	return nil
}

// execWithBusyRetry runs stmt on conn and retries on SQLITE_BUSY until
// deadline. It covers BEGIN IMMEDIATE and COMMIT contention;
// modernc.org/sqlite's busy_timeout does not reliably cover either when
// multiple connections race for the WAL write lock.
func execWithBusyRetry(ctx context.Context, conn *sql.Conn, stmt, label string, deadline time.Time) error {
	return retryOnBusy(ctx, deadline, label, func() error {
		_, err := conn.ExecContext(ctx, stmt)
		return err
	})
}

// retryOnBusy runs op and retries it on SQLITE_BUSY/LOCKED until
// deadline. The same retry shape covers Exec, Query, and any other
// SQLite call that can race the WAL writer lock — including the
// pre-lock user_version read, where the WAL initialization race on a
// fresh DB can BUSY a SELECT that should otherwise succeed under WAL
// reader/writer concurrency.
func retryOnBusy(ctx context.Context, deadline time.Time, label string, op func() error) error {
	backoff := migrationLockBackoffMin
	for {
		err := op()
		if err == nil {
			return nil
		}
		if !isSQLiteBusy(err) {
			return fmt.Errorf("%s: %w", label, err)
		}
		if time.Now().After(deadline) {
			// The label carries the operation context (e.g. "begin
			// migration transaction", "reading schema version") — we
			// don't hardcode "waiting for write lock" because pre-lock
			// reads also flow through this helper.
			return fmt.Errorf("%s: timed out after %s under SQLite contention: %w", label, migrationLockTimeout, err)
		}
		select {
		case <-ctx.Done():
			return fmt.Errorf("%s: %w", label, ctx.Err())
		case <-time.After(backoff):
		}
		backoff = min(backoff*2, migrationLockBackoffMax)
	}
}

// isSQLiteBusy reports whether err is a retryable SQLite lock condition.
// Covers both the file-level WAL writer race (SQLITE_BUSY / "database is
// locked") and the table-level shared-cache contention (SQLITE_LOCKED /
// "database table is locked"). The match is on the error string because
// modernc.org/sqlite does not export an error type the generated code
// can switch on without dragging the driver package into every store
// consumer.
func isSQLiteBusy(err error) bool {
	if err == nil {
		return false
	}
	msg := err.Error()
	return strings.Contains(msg, "SQLITE_BUSY") ||
		strings.Contains(msg, "SQLITE_LOCKED") ||
		strings.Contains(msg, "database is locked") ||
		strings.Contains(msg, "database table is locked")
}

func (s *Store) upsertGenericResourceTx(tx *sql.Tx, resourceType, id string, data json.RawMessage) error {
	_, err := tx.Exec(
		`INSERT INTO resources (id, resource_type, data, synced_at, updated_at)
		 VALUES (?, ?, ?, ?, ?)
		 ON CONFLICT(id) DO UPDATE SET data = excluded.data, synced_at = excluded.synced_at, updated_at = excluded.updated_at`,
		id, resourceType, string(data), time.Now(), time.Now(),
	)
	if err != nil {
		return err
	}

	ftsRowid := ftsRowID(id)
	// Use explicit rowid for FTS5 compatibility with modernc.org/sqlite.
	// Standard DELETE WHERE column=? may not work on FTS5 virtual tables.
	if _, err = tx.Exec(`DELETE FROM resources_fts WHERE rowid = ?`, ftsRowid); err != nil {
		fmt.Fprintf(os.Stderr, "warning: FTS index cleanup failed: %v\n", err)
	}

	if _, err = tx.Exec(
		`INSERT INTO resources_fts (rowid, id, resource_type, content)
		 VALUES (?, ?, ?, ?)`,
		ftsRowid, id, resourceType, string(data),
	); err != nil {
		// FTS insert failure is non-fatal
		fmt.Fprintf(os.Stderr, "warning: FTS index update failed: %v\n", err)
	}

	return nil
}

func (s *Store) Upsert(resourceType, id string, data json.RawMessage) error {
	s.writeMu.Lock()
	defer s.writeMu.Unlock()
	tx, err := s.db.Begin()
	if err != nil {
		return err
	}
	defer tx.Rollback()

	if err := s.upsertGenericResourceTx(tx, resourceType, id, data); err != nil {
		return err
	}

	return tx.Commit()
}

func (s *Store) Get(resourceType, id string) (json.RawMessage, error) {
	var data string
	err := s.db.QueryRow(
		`SELECT data FROM resources WHERE resource_type = ? AND id = ?`,
		resourceType, id,
	).Scan(&data)
	if err == sql.ErrNoRows {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	return json.RawMessage(data), nil
}

func (s *Store) List(resourceType string, limit int) ([]json.RawMessage, error) {
	if limit <= 0 {
		limit = 200
	}
	rows, err := s.db.Query(
		`SELECT data FROM resources WHERE resource_type = ? ORDER BY updated_at DESC LIMIT ?`,
		resourceType, limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var results []json.RawMessage
	for rows.Next() {
		var data string
		if err := rows.Scan(&data); err != nil {
			return nil, err
		}
		results = append(results, json.RawMessage(data))
	}
	return results, rows.Err()
}

func (s *Store) Search(query string, limit int) ([]json.RawMessage, error) {
	if limit <= 0 {
		limit = 50
	}
	rows, err := s.db.Query(
		`SELECT r.data FROM resources r
		 JOIN resources_fts f ON r.id = f.id
		 WHERE resources_fts MATCH ?
		 ORDER BY rank
		 LIMIT ?`,
		query, limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var results []json.RawMessage
	for rows.Next() {
		var data string
		if err := rows.Scan(&data); err != nil {
			return nil, err
		}
		results = append(results, json.RawMessage(data))
	}
	return results, rows.Err()
}

func extractObjectID(obj map[string]any) string {
	for _, key := range []string{"id", "ID", "uuid", "slug", "name"} {
		if v, ok := obj[key]; ok {
			return fmt.Sprintf("%v", v)
		}
	}
	return ""
}

// ftsRowID derives a deterministic rowid from a string ID for use with FTS5.
// modernc.org/sqlite's FTS5 implementation may not support DELETE WHERE column=?
// on virtual tables, so we use explicit rowids and DELETE WHERE rowid=? instead.
func ftsRowID(id string) int64 {
	var h uint64
	for _, c := range id {
		h = h*31 + uint64(c)
	}
	return int64(h & 0x7FFFFFFFFFFFFFFF) // ensure positive
}

// LookupFieldValue resolves a field value from a JSON object map, trying
// the snake_case key first and the camelCase rendering second. Exported so
// the sync command's extractID and the upsert path resolve fields the same
// way — a divergence here produces silent drops on heterogeneous payloads.
func LookupFieldValue(obj map[string]any, snakeKey string) any {
	if v, ok := obj[snakeKey]; ok {
		return sqliteFieldValue(v)
	}
	parts := strings.Split(snakeKey, "_")
	for i := 1; i < len(parts); i++ {
		if parts[i] == "" {
			continue
		}
		parts[i] = strings.ToUpper(parts[i][:1]) + parts[i][1:]
	}
	if v, ok := obj[strings.Join(parts, "")]; ok {
		return sqliteFieldValue(v)
	}
	return nil
}

func sqliteFieldValue(v any) any {
	switch v.(type) {
	case nil, string, bool, int, int64, float64, []byte:
		return v
	default:
		data, err := json.Marshal(v)
		if err != nil {
			return fmt.Sprint(v)
		}
		return string(data)
	}
}

// lookupFieldValue is kept as an unexported alias for in-package callers so
// the existing UpsertBatch code reads naturally without prefixing every call
// with the package name.
func lookupFieldValue(obj map[string]any, snakeKey string) any {
	return LookupFieldValue(obj, snakeKey)
}

// upsertComputersTx writes the typed-table portion of a computers upsert
// inside an existing transaction. The caller is responsible for the generic
// resources insert (via upsertGenericResourceTx) and for committing the tx.
// Splitting this out lets UpsertBatch dispatch typed inserts per item without
// opening a per-item transaction.
func (s *Store) upsertComputersTx(tx *sql.Tx, id string, obj map[string]any, data json.RawMessage) error {
	if _, err := tx.Exec(
		`INSERT INTO computers (id, data, synced_at, connection_url, cpu, created_at, disk_size_gb, fly_instance_id, hostname, name, os, project_name, ram, status, url, vnc_password)
		 VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
		 ON CONFLICT(id) DO UPDATE SET data = excluded.data, synced_at = excluded.synced_at, connection_url = excluded.connection_url, cpu = excluded.cpu, created_at = excluded.created_at, disk_size_gb = excluded.disk_size_gb, fly_instance_id = excluded.fly_instance_id, hostname = excluded.hostname, name = excluded.name, os = excluded.os, project_name = excluded.project_name, ram = excluded.ram, status = excluded.status, url = excluded.url, vnc_password = excluded.vnc_password`,
		id,
		string(data),
		time.Now(),
		lookupFieldValue(obj, "connection_url"),
		lookupFieldValue(obj, "cpu"),
		lookupFieldValue(obj, "created_at"),
		lookupFieldValue(obj, "disk_size_gb"),
		lookupFieldValue(obj, "fly_instance_id"),
		lookupFieldValue(obj, "hostname"),
		lookupFieldValue(obj, "name"),
		lookupFieldValue(obj, "os"),
		lookupFieldValue(obj, "project_name"),
		lookupFieldValue(obj, "ram"),
		lookupFieldValue(obj, "status"),
		lookupFieldValue(obj, "url"),
		lookupFieldValue(obj, "vnc_password"),
	); err != nil {
		return fmt.Errorf("insert into computers: %w", err)
	}

	return nil
}

// UpsertComputers inserts or updates a computers record with domain-specific columns.
func (s *Store) UpsertComputers(data json.RawMessage) error {
	var obj map[string]any
	if err := json.Unmarshal(data, &obj); err != nil {
		return fmt.Errorf("unmarshaling computers: %w", err)
	}

	id := extractObjectID(obj)
	if id == "" {
		return fmt.Errorf("missing id for computers")
	}

	s.writeMu.Lock()
	defer s.writeMu.Unlock()
	tx, err := s.db.Begin()
	if err != nil {
		return err
	}
	defer tx.Rollback()

	if err := s.upsertGenericResourceTx(tx, "computers", id, data); err != nil {
		return err
	}
	if err := s.upsertComputersTx(tx, id, obj, data); err != nil {
		return err
	}

	return tx.Commit()
}

// upsertAutoStopTx writes the typed-table portion of a auto_stop upsert
// inside an existing transaction. The caller is responsible for the generic
// resources insert (via upsertGenericResourceTx) and for committing the tx.
// Splitting this out lets UpsertBatch dispatch typed inserts per item without
// opening a per-item transaction.
func (s *Store) upsertAutoStopTx(tx *sql.Tx, id string, obj map[string]any, data json.RawMessage) error {
	if _, err := tx.Exec(
		`INSERT INTO auto_stop (id, computers_id, data, synced_at)
		 VALUES (?, ?, ?, ?)
		 ON CONFLICT(id) DO UPDATE SET computers_id = excluded.computers_id, data = excluded.data, synced_at = excluded.synced_at`,
		id,
		string(data),
		time.Now(),
		lookupFieldValue(obj, "computers_id"),
	); err != nil {
		return fmt.Errorf("insert into auto_stop: %w", err)
	}

	return nil
}

// UpsertAutoStop inserts or updates a auto_stop record with domain-specific columns.
func (s *Store) UpsertAutoStop(data json.RawMessage) error {
	var obj map[string]any
	if err := json.Unmarshal(data, &obj); err != nil {
		return fmt.Errorf("unmarshaling auto_stop: %w", err)
	}

	id := extractObjectID(obj)
	if id == "" {
		return fmt.Errorf("missing id for auto_stop")
	}

	s.writeMu.Lock()
	defer s.writeMu.Unlock()
	tx, err := s.db.Begin()
	if err != nil {
		return err
	}
	defer tx.Rollback()

	if err := s.upsertGenericResourceTx(tx, "auto_stop", id, data); err != nil {
		return err
	}
	if err := s.upsertAutoStopTx(tx, id, obj, data); err != nil {
		return err
	}

	return tx.Commit()
}

// upsertBashTx writes the typed-table portion of a bash upsert
// inside an existing transaction. The caller is responsible for the generic
// resources insert (via upsertGenericResourceTx) and for committing the tx.
// Splitting this out lets UpsertBatch dispatch typed inserts per item without
// opening a per-item transaction.
func (s *Store) upsertBashTx(tx *sql.Tx, id string, obj map[string]any, data json.RawMessage) error {
	if _, err := tx.Exec(
		`INSERT INTO bash (id, computers_id, data, synced_at)
		 VALUES (?, ?, ?, ?)
		 ON CONFLICT(id) DO UPDATE SET computers_id = excluded.computers_id, data = excluded.data, synced_at = excluded.synced_at`,
		id,
		string(data),
		time.Now(),
		lookupFieldValue(obj, "computers_id"),
	); err != nil {
		return fmt.Errorf("insert into bash: %w", err)
	}

	return nil
}

// UpsertBash inserts or updates a bash record with domain-specific columns.
func (s *Store) UpsertBash(data json.RawMessage) error {
	var obj map[string]any
	if err := json.Unmarshal(data, &obj); err != nil {
		return fmt.Errorf("unmarshaling bash: %w", err)
	}

	id := extractObjectID(obj)
	if id == "" {
		return fmt.Errorf("missing id for bash")
	}

	s.writeMu.Lock()
	defer s.writeMu.Unlock()
	tx, err := s.db.Begin()
	if err != nil {
		return err
	}
	defer tx.Rollback()

	if err := s.upsertGenericResourceTx(tx, "bash", id, data); err != nil {
		return err
	}
	if err := s.upsertBashTx(tx, id, obj, data); err != nil {
		return err
	}

	return tx.Commit()
}

// upsertClickTx writes the typed-table portion of a click upsert
// inside an existing transaction. The caller is responsible for the generic
// resources insert (via upsertGenericResourceTx) and for committing the tx.
// Splitting this out lets UpsertBatch dispatch typed inserts per item without
// opening a per-item transaction.
func (s *Store) upsertClickTx(tx *sql.Tx, id string, obj map[string]any, data json.RawMessage) error {
	if _, err := tx.Exec(
		`INSERT INTO click (id, computers_id, data, synced_at)
		 VALUES (?, ?, ?, ?)
		 ON CONFLICT(id) DO UPDATE SET computers_id = excluded.computers_id, data = excluded.data, synced_at = excluded.synced_at`,
		id,
		string(data),
		time.Now(),
		lookupFieldValue(obj, "computers_id"),
	); err != nil {
		return fmt.Errorf("insert into click: %w", err)
	}

	return nil
}

// UpsertClick inserts or updates a click record with domain-specific columns.
func (s *Store) UpsertClick(data json.RawMessage) error {
	var obj map[string]any
	if err := json.Unmarshal(data, &obj); err != nil {
		return fmt.Errorf("unmarshaling click: %w", err)
	}

	id := extractObjectID(obj)
	if id == "" {
		return fmt.Errorf("missing id for click")
	}

	s.writeMu.Lock()
	defer s.writeMu.Unlock()
	tx, err := s.db.Begin()
	if err != nil {
		return err
	}
	defer tx.Rollback()

	if err := s.upsertGenericResourceTx(tx, "click", id, data); err != nil {
		return err
	}
	if err := s.upsertClickTx(tx, id, obj, data); err != nil {
		return err
	}

	return tx.Commit()
}

// upsertCloneTx writes the typed-table portion of a clone upsert
// inside an existing transaction. The caller is responsible for the generic
// resources insert (via upsertGenericResourceTx) and for committing the tx.
// Splitting this out lets UpsertBatch dispatch typed inserts per item without
// opening a per-item transaction.
func (s *Store) upsertCloneTx(tx *sql.Tx, id string, obj map[string]any, data json.RawMessage) error {
	if _, err := tx.Exec(
		`INSERT INTO clone (id, computers_id, data, synced_at)
		 VALUES (?, ?, ?, ?)
		 ON CONFLICT(id) DO UPDATE SET computers_id = excluded.computers_id, data = excluded.data, synced_at = excluded.synced_at`,
		id,
		string(data),
		time.Now(),
		lookupFieldValue(obj, "computers_id"),
	); err != nil {
		return fmt.Errorf("insert into clone: %w", err)
	}

	return nil
}

// UpsertClone inserts or updates a clone record with domain-specific columns.
func (s *Store) UpsertClone(data json.RawMessage) error {
	var obj map[string]any
	if err := json.Unmarshal(data, &obj); err != nil {
		return fmt.Errorf("unmarshaling clone: %w", err)
	}

	id := extractObjectID(obj)
	if id == "" {
		return fmt.Errorf("missing id for clone")
	}

	s.writeMu.Lock()
	defer s.writeMu.Unlock()
	tx, err := s.db.Begin()
	if err != nil {
		return err
	}
	defer tx.Rollback()

	if err := s.upsertGenericResourceTx(tx, "clone", id, data); err != nil {
		return err
	}
	if err := s.upsertCloneTx(tx, id, obj, data); err != nil {
		return err
	}

	return tx.Commit()
}

// upsertDragTx writes the typed-table portion of a drag upsert
// inside an existing transaction. The caller is responsible for the generic
// resources insert (via upsertGenericResourceTx) and for committing the tx.
// Splitting this out lets UpsertBatch dispatch typed inserts per item without
// opening a per-item transaction.
func (s *Store) upsertDragTx(tx *sql.Tx, id string, obj map[string]any, data json.RawMessage) error {
	if _, err := tx.Exec(
		`INSERT INTO drag (id, computers_id, data, synced_at)
		 VALUES (?, ?, ?, ?)
		 ON CONFLICT(id) DO UPDATE SET computers_id = excluded.computers_id, data = excluded.data, synced_at = excluded.synced_at`,
		id,
		string(data),
		time.Now(),
		lookupFieldValue(obj, "computers_id"),
	); err != nil {
		return fmt.Errorf("insert into drag: %w", err)
	}

	return nil
}

// UpsertDrag inserts or updates a drag record with domain-specific columns.
func (s *Store) UpsertDrag(data json.RawMessage) error {
	var obj map[string]any
	if err := json.Unmarshal(data, &obj); err != nil {
		return fmt.Errorf("unmarshaling drag: %w", err)
	}

	id := extractObjectID(obj)
	if id == "" {
		return fmt.Errorf("missing id for drag")
	}

	s.writeMu.Lock()
	defer s.writeMu.Unlock()
	tx, err := s.db.Begin()
	if err != nil {
		return err
	}
	defer tx.Rollback()

	if err := s.upsertGenericResourceTx(tx, "drag", id, data); err != nil {
		return err
	}
	if err := s.upsertDragTx(tx, id, obj, data); err != nil {
		return err
	}

	return tx.Commit()
}

// upsertExecTx writes the typed-table portion of a exec upsert
// inside an existing transaction. The caller is responsible for the generic
// resources insert (via upsertGenericResourceTx) and for committing the tx.
// Splitting this out lets UpsertBatch dispatch typed inserts per item without
// opening a per-item transaction.
func (s *Store) upsertExecTx(tx *sql.Tx, id string, obj map[string]any, data json.RawMessage) error {
	if _, err := tx.Exec(
		`INSERT INTO exec (id, computers_id, data, synced_at)
		 VALUES (?, ?, ?, ?)
		 ON CONFLICT(id) DO UPDATE SET computers_id = excluded.computers_id, data = excluded.data, synced_at = excluded.synced_at`,
		id,
		string(data),
		time.Now(),
		lookupFieldValue(obj, "computers_id"),
	); err != nil {
		return fmt.Errorf("insert into exec: %w", err)
	}

	return nil
}

// UpsertExec inserts or updates a exec record with domain-specific columns.
func (s *Store) UpsertExec(data json.RawMessage) error {
	var obj map[string]any
	if err := json.Unmarshal(data, &obj); err != nil {
		return fmt.Errorf("unmarshaling exec: %w", err)
	}

	id := extractObjectID(obj)
	if id == "" {
		return fmt.Errorf("missing id for exec")
	}

	s.writeMu.Lock()
	defer s.writeMu.Unlock()
	tx, err := s.db.Begin()
	if err != nil {
		return err
	}
	defer tx.Rollback()

	if err := s.upsertGenericResourceTx(tx, "exec", id, data); err != nil {
		return err
	}
	if err := s.upsertExecTx(tx, id, obj, data); err != nil {
		return err
	}

	return tx.Commit()
}

// upsertKeyTx writes the typed-table portion of a key upsert
// inside an existing transaction. The caller is responsible for the generic
// resources insert (via upsertGenericResourceTx) and for committing the tx.
// Splitting this out lets UpsertBatch dispatch typed inserts per item without
// opening a per-item transaction.
func (s *Store) upsertKeyTx(tx *sql.Tx, id string, obj map[string]any, data json.RawMessage) error {
	if _, err := tx.Exec(
		`INSERT INTO "key" (id, computers_id, data, synced_at)
		 VALUES (?, ?, ?, ?)
		 ON CONFLICT(id) DO UPDATE SET computers_id = excluded.computers_id, data = excluded.data, synced_at = excluded.synced_at`,
		id,
		string(data),
		time.Now(),
		lookupFieldValue(obj, "computers_id"),
	); err != nil {
		return fmt.Errorf("insert into key: %w", err)
	}

	return nil
}

// UpsertKey inserts or updates a key record with domain-specific columns.
func (s *Store) UpsertKey(data json.RawMessage) error {
	var obj map[string]any
	if err := json.Unmarshal(data, &obj); err != nil {
		return fmt.Errorf("unmarshaling key: %w", err)
	}

	id := extractObjectID(obj)
	if id == "" {
		return fmt.Errorf("missing id for key")
	}

	s.writeMu.Lock()
	defer s.writeMu.Unlock()
	tx, err := s.db.Begin()
	if err != nil {
		return err
	}
	defer tx.Rollback()

	if err := s.upsertGenericResourceTx(tx, "key", id, data); err != nil {
		return err
	}
	if err := s.upsertKeyTx(tx, id, obj, data); err != nil {
		return err
	}

	return tx.Commit()
}

// upsertMoveTx writes the typed-table portion of a move upsert
// inside an existing transaction. The caller is responsible for the generic
// resources insert (via upsertGenericResourceTx) and for committing the tx.
// Splitting this out lets UpsertBatch dispatch typed inserts per item without
// opening a per-item transaction.
func (s *Store) upsertMoveTx(tx *sql.Tx, id string, obj map[string]any, data json.RawMessage) error {
	if _, err := tx.Exec(
		`INSERT INTO move (id, computers_id, data, synced_at)
		 VALUES (?, ?, ?, ?)
		 ON CONFLICT(id) DO UPDATE SET computers_id = excluded.computers_id, data = excluded.data, synced_at = excluded.synced_at`,
		id,
		string(data),
		time.Now(),
		lookupFieldValue(obj, "computers_id"),
	); err != nil {
		return fmt.Errorf("insert into move: %w", err)
	}

	return nil
}

// UpsertMove inserts or updates a move record with domain-specific columns.
func (s *Store) UpsertMove(data json.RawMessage) error {
	var obj map[string]any
	if err := json.Unmarshal(data, &obj); err != nil {
		return fmt.Errorf("unmarshaling move: %w", err)
	}

	id := extractObjectID(obj)
	if id == "" {
		return fmt.Errorf("missing id for move")
	}

	s.writeMu.Lock()
	defer s.writeMu.Unlock()
	tx, err := s.db.Begin()
	if err != nil {
		return err
	}
	defer tx.Rollback()

	if err := s.upsertGenericResourceTx(tx, "move", id, data); err != nil {
		return err
	}
	if err := s.upsertMoveTx(tx, id, obj, data); err != nil {
		return err
	}

	return tx.Commit()
}

// upsertResizeTx writes the typed-table portion of a resize upsert
// inside an existing transaction. The caller is responsible for the generic
// resources insert (via upsertGenericResourceTx) and for committing the tx.
// Splitting this out lets UpsertBatch dispatch typed inserts per item without
// opening a per-item transaction.
func (s *Store) upsertResizeTx(tx *sql.Tx, id string, obj map[string]any, data json.RawMessage) error {
	if _, err := tx.Exec(
		`INSERT INTO resize (id, computers_id, data, synced_at)
		 VALUES (?, ?, ?, ?)
		 ON CONFLICT(id) DO UPDATE SET computers_id = excluded.computers_id, data = excluded.data, synced_at = excluded.synced_at`,
		id,
		string(data),
		time.Now(),
		lookupFieldValue(obj, "computers_id"),
	); err != nil {
		return fmt.Errorf("insert into resize: %w", err)
	}

	return nil
}

// UpsertResize inserts or updates a resize record with domain-specific columns.
func (s *Store) UpsertResize(data json.RawMessage) error {
	var obj map[string]any
	if err := json.Unmarshal(data, &obj); err != nil {
		return fmt.Errorf("unmarshaling resize: %w", err)
	}

	id := extractObjectID(obj)
	if id == "" {
		return fmt.Errorf("missing id for resize")
	}

	s.writeMu.Lock()
	defer s.writeMu.Unlock()
	tx, err := s.db.Begin()
	if err != nil {
		return err
	}
	defer tx.Rollback()

	if err := s.upsertGenericResourceTx(tx, "resize", id, data); err != nil {
		return err
	}
	if err := s.upsertResizeTx(tx, id, obj, data); err != nil {
		return err
	}

	return tx.Commit()
}

// upsertRestartTx writes the typed-table portion of a restart upsert
// inside an existing transaction. The caller is responsible for the generic
// resources insert (via upsertGenericResourceTx) and for committing the tx.
// Splitting this out lets UpsertBatch dispatch typed inserts per item without
// opening a per-item transaction.
func (s *Store) upsertRestartTx(tx *sql.Tx, id string, obj map[string]any, data json.RawMessage) error {
	if _, err := tx.Exec(
		`INSERT INTO restart (id, computers_id, data, synced_at)
		 VALUES (?, ?, ?, ?)
		 ON CONFLICT(id) DO UPDATE SET computers_id = excluded.computers_id, data = excluded.data, synced_at = excluded.synced_at`,
		id,
		string(data),
		time.Now(),
		lookupFieldValue(obj, "computers_id"),
	); err != nil {
		return fmt.Errorf("insert into restart: %w", err)
	}

	return nil
}

// UpsertRestart inserts or updates a restart record with domain-specific columns.
func (s *Store) UpsertRestart(data json.RawMessage) error {
	var obj map[string]any
	if err := json.Unmarshal(data, &obj); err != nil {
		return fmt.Errorf("unmarshaling restart: %w", err)
	}

	id := extractObjectID(obj)
	if id == "" {
		return fmt.Errorf("missing id for restart")
	}

	s.writeMu.Lock()
	defer s.writeMu.Unlock()
	tx, err := s.db.Begin()
	if err != nil {
		return err
	}
	defer tx.Rollback()

	if err := s.upsertGenericResourceTx(tx, "restart", id, data); err != nil {
		return err
	}
	if err := s.upsertRestartTx(tx, id, obj, data); err != nil {
		return err
	}

	return tx.Commit()
}

// upsertScreenshotTx writes the typed-table portion of a screenshot upsert
// inside an existing transaction. The caller is responsible for the generic
// resources insert (via upsertGenericResourceTx) and for committing the tx.
// Splitting this out lets UpsertBatch dispatch typed inserts per item without
// opening a per-item transaction.
func (s *Store) upsertScreenshotTx(tx *sql.Tx, id string, obj map[string]any, data json.RawMessage) error {
	if _, err := tx.Exec(
		`INSERT INTO screenshot (id, computers_id, data, synced_at)
		 VALUES (?, ?, ?, ?)
		 ON CONFLICT(id) DO UPDATE SET computers_id = excluded.computers_id, data = excluded.data, synced_at = excluded.synced_at`,
		id,
		string(data),
		time.Now(),
		lookupFieldValue(obj, "computers_id"),
	); err != nil {
		return fmt.Errorf("insert into screenshot: %w", err)
	}

	return nil
}

// UpsertScreenshot inserts or updates a screenshot record with domain-specific columns.
func (s *Store) UpsertScreenshot(data json.RawMessage) error {
	var obj map[string]any
	if err := json.Unmarshal(data, &obj); err != nil {
		return fmt.Errorf("unmarshaling screenshot: %w", err)
	}

	id := extractObjectID(obj)
	if id == "" {
		return fmt.Errorf("missing id for screenshot")
	}

	s.writeMu.Lock()
	defer s.writeMu.Unlock()
	tx, err := s.db.Begin()
	if err != nil {
		return err
	}
	defer tx.Rollback()

	if err := s.upsertGenericResourceTx(tx, "screenshot", id, data); err != nil {
		return err
	}
	if err := s.upsertScreenshotTx(tx, id, obj, data); err != nil {
		return err
	}

	return tx.Commit()
}

// upsertScrollTx writes the typed-table portion of a scroll upsert
// inside an existing transaction. The caller is responsible for the generic
// resources insert (via upsertGenericResourceTx) and for committing the tx.
// Splitting this out lets UpsertBatch dispatch typed inserts per item without
// opening a per-item transaction.
func (s *Store) upsertScrollTx(tx *sql.Tx, id string, obj map[string]any, data json.RawMessage) error {
	if _, err := tx.Exec(
		`INSERT INTO scroll (id, computers_id, data, synced_at)
		 VALUES (?, ?, ?, ?)
		 ON CONFLICT(id) DO UPDATE SET computers_id = excluded.computers_id, data = excluded.data, synced_at = excluded.synced_at`,
		id,
		string(data),
		time.Now(),
		lookupFieldValue(obj, "computers_id"),
	); err != nil {
		return fmt.Errorf("insert into scroll: %w", err)
	}

	return nil
}

// UpsertScroll inserts or updates a scroll record with domain-specific columns.
func (s *Store) UpsertScroll(data json.RawMessage) error {
	var obj map[string]any
	if err := json.Unmarshal(data, &obj); err != nil {
		return fmt.Errorf("unmarshaling scroll: %w", err)
	}

	id := extractObjectID(obj)
	if id == "" {
		return fmt.Errorf("missing id for scroll")
	}

	s.writeMu.Lock()
	defer s.writeMu.Unlock()
	tx, err := s.db.Begin()
	if err != nil {
		return err
	}
	defer tx.Rollback()

	if err := s.upsertGenericResourceTx(tx, "scroll", id, data); err != nil {
		return err
	}
	if err := s.upsertScrollTx(tx, id, obj, data); err != nil {
		return err
	}

	return tx.Commit()
}

// upsertStartTx writes the typed-table portion of a start upsert
// inside an existing transaction. The caller is responsible for the generic
// resources insert (via upsertGenericResourceTx) and for committing the tx.
// Splitting this out lets UpsertBatch dispatch typed inserts per item without
// opening a per-item transaction.
func (s *Store) upsertStartTx(tx *sql.Tx, id string, obj map[string]any, data json.RawMessage) error {
	if _, err := tx.Exec(
		`INSERT INTO start (id, computers_id, data, synced_at)
		 VALUES (?, ?, ?, ?)
		 ON CONFLICT(id) DO UPDATE SET computers_id = excluded.computers_id, data = excluded.data, synced_at = excluded.synced_at`,
		id,
		string(data),
		time.Now(),
		lookupFieldValue(obj, "computers_id"),
	); err != nil {
		return fmt.Errorf("insert into start: %w", err)
	}

	return nil
}

// UpsertStart inserts or updates a start record with domain-specific columns.
func (s *Store) UpsertStart(data json.RawMessage) error {
	var obj map[string]any
	if err := json.Unmarshal(data, &obj); err != nil {
		return fmt.Errorf("unmarshaling start: %w", err)
	}

	id := extractObjectID(obj)
	if id == "" {
		return fmt.Errorf("missing id for start")
	}

	s.writeMu.Lock()
	defer s.writeMu.Unlock()
	tx, err := s.db.Begin()
	if err != nil {
		return err
	}
	defer tx.Rollback()

	if err := s.upsertGenericResourceTx(tx, "start", id, data); err != nil {
		return err
	}
	if err := s.upsertStartTx(tx, id, obj, data); err != nil {
		return err
	}

	return tx.Commit()
}

// upsertStopTx writes the typed-table portion of a stop upsert
// inside an existing transaction. The caller is responsible for the generic
// resources insert (via upsertGenericResourceTx) and for committing the tx.
// Splitting this out lets UpsertBatch dispatch typed inserts per item without
// opening a per-item transaction.
func (s *Store) upsertStopTx(tx *sql.Tx, id string, obj map[string]any, data json.RawMessage) error {
	if _, err := tx.Exec(
		`INSERT INTO stop (id, computers_id, data, synced_at)
		 VALUES (?, ?, ?, ?)
		 ON CONFLICT(id) DO UPDATE SET computers_id = excluded.computers_id, data = excluded.data, synced_at = excluded.synced_at`,
		id,
		string(data),
		time.Now(),
		lookupFieldValue(obj, "computers_id"),
	); err != nil {
		return fmt.Errorf("insert into stop: %w", err)
	}

	return nil
}

// UpsertStop inserts or updates a stop record with domain-specific columns.
func (s *Store) UpsertStop(data json.RawMessage) error {
	var obj map[string]any
	if err := json.Unmarshal(data, &obj); err != nil {
		return fmt.Errorf("unmarshaling stop: %w", err)
	}

	id := extractObjectID(obj)
	if id == "" {
		return fmt.Errorf("missing id for stop")
	}

	s.writeMu.Lock()
	defer s.writeMu.Unlock()
	tx, err := s.db.Begin()
	if err != nil {
		return err
	}
	defer tx.Rollback()

	if err := s.upsertGenericResourceTx(tx, "stop", id, data); err != nil {
		return err
	}
	if err := s.upsertStopTx(tx, id, obj, data); err != nil {
		return err
	}

	return tx.Commit()
}

// upsertStreamTx writes the typed-table portion of a stream upsert
// inside an existing transaction. The caller is responsible for the generic
// resources insert (via upsertGenericResourceTx) and for committing the tx.
// Splitting this out lets UpsertBatch dispatch typed inserts per item without
// opening a per-item transaction.
func (s *Store) upsertStreamTx(tx *sql.Tx, id string, obj map[string]any, data json.RawMessage) error {
	if _, err := tx.Exec(
		`INSERT INTO stream (id, computers_id, data, synced_at)
		 VALUES (?, ?, ?, ?)
		 ON CONFLICT(id) DO UPDATE SET computers_id = excluded.computers_id, data = excluded.data, synced_at = excluded.synced_at`,
		id,
		string(data),
		time.Now(),
		lookupFieldValue(obj, "computers_id"),
	); err != nil {
		return fmt.Errorf("insert into stream: %w", err)
	}

	return nil
}

// UpsertStream inserts or updates a stream record with domain-specific columns.
func (s *Store) UpsertStream(data json.RawMessage) error {
	var obj map[string]any
	if err := json.Unmarshal(data, &obj); err != nil {
		return fmt.Errorf("unmarshaling stream: %w", err)
	}

	id := extractObjectID(obj)
	if id == "" {
		return fmt.Errorf("missing id for stream")
	}

	s.writeMu.Lock()
	defer s.writeMu.Unlock()
	tx, err := s.db.Begin()
	if err != nil {
		return err
	}
	defer tx.Rollback()

	if err := s.upsertGenericResourceTx(tx, "stream", id, data); err != nil {
		return err
	}
	if err := s.upsertStreamTx(tx, id, obj, data); err != nil {
		return err
	}

	return tx.Commit()
}

// upsertTypeTx writes the typed-table portion of a type upsert
// inside an existing transaction. The caller is responsible for the generic
// resources insert (via upsertGenericResourceTx) and for committing the tx.
// Splitting this out lets UpsertBatch dispatch typed inserts per item without
// opening a per-item transaction.
func (s *Store) upsertTypeTx(tx *sql.Tx, id string, obj map[string]any, data json.RawMessage) error {
	if _, err := tx.Exec(
		`INSERT INTO type (id, computers_id, data, synced_at)
		 VALUES (?, ?, ?, ?)
		 ON CONFLICT(id) DO UPDATE SET computers_id = excluded.computers_id, data = excluded.data, synced_at = excluded.synced_at`,
		id,
		string(data),
		time.Now(),
		lookupFieldValue(obj, "computers_id"),
	); err != nil {
		return fmt.Errorf("insert into type: %w", err)
	}

	return nil
}

// UpsertType inserts or updates a type record with domain-specific columns.
func (s *Store) UpsertType(data json.RawMessage) error {
	var obj map[string]any
	if err := json.Unmarshal(data, &obj); err != nil {
		return fmt.Errorf("unmarshaling type: %w", err)
	}

	id := extractObjectID(obj)
	if id == "" {
		return fmt.Errorf("missing id for type")
	}

	s.writeMu.Lock()
	defer s.writeMu.Unlock()
	tx, err := s.db.Begin()
	if err != nil {
		return err
	}
	defer tx.Rollback()

	if err := s.upsertGenericResourceTx(tx, "type", id, data); err != nil {
		return err
	}
	if err := s.upsertTypeTx(tx, id, obj, data); err != nil {
		return err
	}

	return tx.Commit()
}

// upsertVncPasswordTx writes the typed-table portion of a vnc_password upsert
// inside an existing transaction. The caller is responsible for the generic
// resources insert (via upsertGenericResourceTx) and for committing the tx.
// Splitting this out lets UpsertBatch dispatch typed inserts per item without
// opening a per-item transaction.
func (s *Store) upsertVncPasswordTx(tx *sql.Tx, id string, obj map[string]any, data json.RawMessage) error {
	if _, err := tx.Exec(
		`INSERT INTO vnc_password (id, computers_id, data, synced_at)
		 VALUES (?, ?, ?, ?)
		 ON CONFLICT(id) DO UPDATE SET computers_id = excluded.computers_id, data = excluded.data, synced_at = excluded.synced_at`,
		id,
		string(data),
		time.Now(),
		lookupFieldValue(obj, "computers_id"),
	); err != nil {
		return fmt.Errorf("insert into vnc_password: %w", err)
	}

	return nil
}

// UpsertVncPassword inserts or updates a vnc_password record with domain-specific columns.
func (s *Store) UpsertVncPassword(data json.RawMessage) error {
	var obj map[string]any
	if err := json.Unmarshal(data, &obj); err != nil {
		return fmt.Errorf("unmarshaling vnc_password: %w", err)
	}

	id := extractObjectID(obj)
	if id == "" {
		return fmt.Errorf("missing id for vnc_password")
	}

	s.writeMu.Lock()
	defer s.writeMu.Unlock()
	tx, err := s.db.Begin()
	if err != nil {
		return err
	}
	defer tx.Rollback()

	if err := s.upsertGenericResourceTx(tx, "vnc_password", id, data); err != nil {
		return err
	}
	if err := s.upsertVncPasswordTx(tx, id, obj, data); err != nil {
		return err
	}

	return tx.Commit()
}

// upsertWaitTx writes the typed-table portion of a wait upsert
// inside an existing transaction. The caller is responsible for the generic
// resources insert (via upsertGenericResourceTx) and for committing the tx.
// Splitting this out lets UpsertBatch dispatch typed inserts per item without
// opening a per-item transaction.
func (s *Store) upsertWaitTx(tx *sql.Tx, id string, obj map[string]any, data json.RawMessage) error {
	if _, err := tx.Exec(
		`INSERT INTO wait (id, computers_id, data, synced_at)
		 VALUES (?, ?, ?, ?)
		 ON CONFLICT(id) DO UPDATE SET computers_id = excluded.computers_id, data = excluded.data, synced_at = excluded.synced_at`,
		id,
		string(data),
		time.Now(),
		lookupFieldValue(obj, "computers_id"),
	); err != nil {
		return fmt.Errorf("insert into wait: %w", err)
	}

	return nil
}

// UpsertWait inserts or updates a wait record with domain-specific columns.
func (s *Store) UpsertWait(data json.RawMessage) error {
	var obj map[string]any
	if err := json.Unmarshal(data, &obj); err != nil {
		return fmt.Errorf("unmarshaling wait: %w", err)
	}

	id := extractObjectID(obj)
	if id == "" {
		return fmt.Errorf("missing id for wait")
	}

	s.writeMu.Lock()
	defer s.writeMu.Unlock()
	tx, err := s.db.Begin()
	if err != nil {
		return err
	}
	defer tx.Rollback()

	if err := s.upsertGenericResourceTx(tx, "wait", id, data); err != nil {
		return err
	}
	if err := s.upsertWaitTx(tx, id, obj, data); err != nil {
		return err
	}

	return tx.Commit()
}

// upsertFilesTx writes the typed-table portion of a files upsert
// inside an existing transaction. The caller is responsible for the generic
// resources insert (via upsertGenericResourceTx) and for committing the tx.
// Splitting this out lets UpsertBatch dispatch typed inserts per item without
// opening a per-item transaction.
func (s *Store) upsertFilesTx(tx *sql.Tx, id string, obj map[string]any, data json.RawMessage) error {
	if _, err := tx.Exec(
		`INSERT INTO files (id, data, synced_at, url)
		 VALUES (?, ?, ?, ?)
		 ON CONFLICT(id) DO UPDATE SET data = excluded.data, synced_at = excluded.synced_at, url = excluded.url`,
		id,
		string(data),
		time.Now(),
		lookupFieldValue(obj, "url"),
	); err != nil {
		return fmt.Errorf("insert into files: %w", err)
	}

	return nil
}

// UpsertFiles inserts or updates a files record with domain-specific columns.
func (s *Store) UpsertFiles(data json.RawMessage) error {
	var obj map[string]any
	if err := json.Unmarshal(data, &obj); err != nil {
		return fmt.Errorf("unmarshaling files: %w", err)
	}

	id := extractObjectID(obj)
	if id == "" {
		return fmt.Errorf("missing id for files")
	}

	s.writeMu.Lock()
	defer s.writeMu.Unlock()
	tx, err := s.db.Begin()
	if err != nil {
		return err
	}
	defer tx.Rollback()

	if err := s.upsertGenericResourceTx(tx, "files", id, data); err != nil {
		return err
	}
	if err := s.upsertFilesTx(tx, id, obj, data); err != nil {
		return err
	}

	return tx.Commit()
}

// upsertWorkspacesTx writes the typed-table portion of a workspaces upsert
// inside an existing transaction. The caller is responsible for the generic
// resources insert (via upsertGenericResourceTx) and for committing the tx.
// Splitting this out lets UpsertBatch dispatch typed inserts per item without
// opening a per-item transaction.
func (s *Store) upsertWorkspacesTx(tx *sql.Tx, id string, obj map[string]any, data json.RawMessage) error {
	if _, err := tx.Exec(
		`INSERT INTO workspaces (id, data, synced_at, created_at, icon_url, name, status, updated_at, user_id)
		 VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
		 ON CONFLICT(id) DO UPDATE SET data = excluded.data, synced_at = excluded.synced_at, created_at = excluded.created_at, icon_url = excluded.icon_url, name = excluded.name, status = excluded.status, updated_at = excluded.updated_at, user_id = excluded.user_id`,
		id,
		string(data),
		time.Now(),
		lookupFieldValue(obj, "created_at"),
		lookupFieldValue(obj, "icon_url"),
		lookupFieldValue(obj, "name"),
		lookupFieldValue(obj, "status"),
		lookupFieldValue(obj, "updated_at"),
		lookupFieldValue(obj, "user_id"),
	); err != nil {
		return fmt.Errorf("insert into workspaces: %w", err)
	}

	return nil
}

// UpsertWorkspaces inserts or updates a workspaces record with domain-specific columns.
func (s *Store) UpsertWorkspaces(data json.RawMessage) error {
	var obj map[string]any
	if err := json.Unmarshal(data, &obj); err != nil {
		return fmt.Errorf("unmarshaling workspaces: %w", err)
	}

	id := extractObjectID(obj)
	if id == "" {
		return fmt.Errorf("missing id for workspaces")
	}

	s.writeMu.Lock()
	defer s.writeMu.Unlock()
	tx, err := s.db.Begin()
	if err != nil {
		return err
	}
	defer tx.Rollback()

	if err := s.upsertGenericResourceTx(tx, "workspaces", id, data); err != nil {
		return err
	}
	if err := s.upsertWorkspacesTx(tx, id, obj, data); err != nil {
		return err
	}

	return tx.Commit()
}

// resourceIDFieldOverrides projects per-resource IDField (set by the profiler
// from x-resource-id or response-schema fallback) into a runtime lookup map.
// UpsertBatch consults this first so the templated path wins over the
// generic fallback list. Empty when no resource declared an override; the
// runtime fallback list still applies.
//
// Includes both flat resources and dependent (parent-child) resources so a
// child path-item annotated with x-resource-id resolves the same as a flat
// path-item.
var resourceIDFieldOverrides = map[string]string{
	"workspaces": "id",
}

// genericIDFieldFallbacks is the runtime safety net for resources that did
// NOT receive a templated IDField. API-specific names belong in spec
// annotations (x-resource-id), not this list.
var genericIDFieldFallbacks = []string{"id", "ID", "name", "uuid", "slug", "key", "code", "uid"}

// UpsertBatch inserts or replaces multiple records in a single transaction
// and returns (stored, extractFailures, err). stored counts rows actually
// landed; extractFailures counts items that survived JSON unmarshal but had
// no extractable primary key (templated IDField AND generic fallback both
// missed). callers (sync.go.tmpl) compare these against len(items) to emit
// the per-item primary_key_unresolved warning and the F4b
// stored_count_zero_after_extraction probe.
//
// For resource types that have a domain-specific typed table, the per-item
// generic insert is followed by a dispatch to the matching upsert<Pascal>Tx
// inside the same transaction. Without that dispatch, paginated syncs would
// only populate the generic resources table — typed tables (and indexed
// columns like parent_id added by dependent-resource sync) would stay empty.
func (s *Store) UpsertBatch(resourceType string, items []json.RawMessage) (int, int, error) {
	s.writeMu.Lock()
	defer s.writeMu.Unlock()
	tx, err := s.db.Begin()
	if err != nil {
		return 0, 0, fmt.Errorf("starting batch transaction: %w", err)
	}
	defer tx.Rollback()

	var stored, skippedCount, extractFailures int
	for _, item := range items {
		var obj map[string]any
		if err := json.Unmarshal(item, &obj); err != nil {
			skippedCount++
			continue
		}
		// Templated IDField wins; generic fallback list runs second when
		// the override is empty OR the override field is absent on this
		// particular item (response shape mismatches happen even when the
		// spec declares x-resource-id).
		var id string
		if override, ok := resourceIDFieldOverrides[resourceType]; ok && override != "" {
			if v := lookupFieldValue(obj, override); v != nil {
				s := fmt.Sprintf("%v", v)
				if s != "" && s != "<nil>" {
					id = s
				}
			}
		}
		if id == "" {
			for _, key := range genericIDFieldFallbacks {
				if v := lookupFieldValue(obj, key); v != nil {
					s := fmt.Sprintf("%v", v)
					if s != "" && s != "<nil>" {
						id = s
						break
					}
				}
			}
		}
		if id == "" {
			skippedCount++
			extractFailures++
			continue
		}

		if err := s.upsertGenericResourceTx(tx, resourceType, id, item); err != nil {
			return 0, extractFailures, fmt.Errorf("upserting %s/%s: %w", resourceType, id, err)
		}

		switch resourceType {
		case "computers":
			if err := s.upsertComputersTx(tx, id, obj, item); err != nil {
				return 0, extractFailures, fmt.Errorf("typed upsert for %s/%s: %w", resourceType, id, err)
			}
		case "auto_stop":
			if err := s.upsertAutoStopTx(tx, id, obj, item); err != nil {
				return 0, extractFailures, fmt.Errorf("typed upsert for %s/%s: %w", resourceType, id, err)
			}
		case "bash":
			if err := s.upsertBashTx(tx, id, obj, item); err != nil {
				return 0, extractFailures, fmt.Errorf("typed upsert for %s/%s: %w", resourceType, id, err)
			}
		case "click":
			if err := s.upsertClickTx(tx, id, obj, item); err != nil {
				return 0, extractFailures, fmt.Errorf("typed upsert for %s/%s: %w", resourceType, id, err)
			}
		case "clone":
			if err := s.upsertCloneTx(tx, id, obj, item); err != nil {
				return 0, extractFailures, fmt.Errorf("typed upsert for %s/%s: %w", resourceType, id, err)
			}
		case "drag":
			if err := s.upsertDragTx(tx, id, obj, item); err != nil {
				return 0, extractFailures, fmt.Errorf("typed upsert for %s/%s: %w", resourceType, id, err)
			}
		case "exec":
			if err := s.upsertExecTx(tx, id, obj, item); err != nil {
				return 0, extractFailures, fmt.Errorf("typed upsert for %s/%s: %w", resourceType, id, err)
			}
		case "key":
			if err := s.upsertKeyTx(tx, id, obj, item); err != nil {
				return 0, extractFailures, fmt.Errorf("typed upsert for %s/%s: %w", resourceType, id, err)
			}
		case "move":
			if err := s.upsertMoveTx(tx, id, obj, item); err != nil {
				return 0, extractFailures, fmt.Errorf("typed upsert for %s/%s: %w", resourceType, id, err)
			}
		case "resize":
			if err := s.upsertResizeTx(tx, id, obj, item); err != nil {
				return 0, extractFailures, fmt.Errorf("typed upsert for %s/%s: %w", resourceType, id, err)
			}
		case "restart":
			if err := s.upsertRestartTx(tx, id, obj, item); err != nil {
				return 0, extractFailures, fmt.Errorf("typed upsert for %s/%s: %w", resourceType, id, err)
			}
		case "screenshot":
			if err := s.upsertScreenshotTx(tx, id, obj, item); err != nil {
				return 0, extractFailures, fmt.Errorf("typed upsert for %s/%s: %w", resourceType, id, err)
			}
		case "scroll":
			if err := s.upsertScrollTx(tx, id, obj, item); err != nil {
				return 0, extractFailures, fmt.Errorf("typed upsert for %s/%s: %w", resourceType, id, err)
			}
		case "start":
			if err := s.upsertStartTx(tx, id, obj, item); err != nil {
				return 0, extractFailures, fmt.Errorf("typed upsert for %s/%s: %w", resourceType, id, err)
			}
		case "stop":
			if err := s.upsertStopTx(tx, id, obj, item); err != nil {
				return 0, extractFailures, fmt.Errorf("typed upsert for %s/%s: %w", resourceType, id, err)
			}
		case "stream":
			if err := s.upsertStreamTx(tx, id, obj, item); err != nil {
				return 0, extractFailures, fmt.Errorf("typed upsert for %s/%s: %w", resourceType, id, err)
			}
		case "type":
			if err := s.upsertTypeTx(tx, id, obj, item); err != nil {
				return 0, extractFailures, fmt.Errorf("typed upsert for %s/%s: %w", resourceType, id, err)
			}
		case "vnc_password":
			if err := s.upsertVncPasswordTx(tx, id, obj, item); err != nil {
				return 0, extractFailures, fmt.Errorf("typed upsert for %s/%s: %w", resourceType, id, err)
			}
		case "wait":
			if err := s.upsertWaitTx(tx, id, obj, item); err != nil {
				return 0, extractFailures, fmt.Errorf("typed upsert for %s/%s: %w", resourceType, id, err)
			}
		case "files":
			if err := s.upsertFilesTx(tx, id, obj, item); err != nil {
				return 0, extractFailures, fmt.Errorf("typed upsert for %s/%s: %w", resourceType, id, err)
			}
		case "workspaces":
			if err := s.upsertWorkspacesTx(tx, id, obj, item); err != nil {
				return 0, extractFailures, fmt.Errorf("typed upsert for %s/%s: %w", resourceType, id, err)
			}
		}
		stored++
	}

	// Warn when most items in a batch lack an extractable ID — this likely
	// means the API uses a primary key field we don't recognize yet.
	if skippedCount > 0 && len(items) > 0 && skippedCount*2 > len(items) {
		fmt.Fprintf(os.Stderr, "warning: %d/%d %s items skipped (no extractable ID field found)\n", skippedCount, len(items), resourceType)
	}

	if err := tx.Commit(); err != nil {
		return 0, extractFailures, err
	}
	return stored, extractFailures, nil
}

func (s *Store) SaveSyncState(resourceType, cursor string, count int) error {
	s.writeMu.Lock()
	defer s.writeMu.Unlock()
	_, err := s.db.Exec(
		`INSERT INTO sync_state (resource_type, last_cursor, last_synced_at, total_count)
		 VALUES (?, ?, ?, ?)
		 ON CONFLICT(resource_type) DO UPDATE SET last_cursor = excluded.last_cursor,
		 last_synced_at = excluded.last_synced_at, total_count = excluded.total_count`,
		resourceType, cursor, time.Now(), count,
	)
	return err
}

func (s *Store) GetSyncState(resourceType string) (cursor string, lastSynced time.Time, count int, err error) {
	err = s.db.QueryRow(
		`SELECT last_cursor, last_synced_at, total_count FROM sync_state WHERE resource_type = ?`,
		resourceType,
	).Scan(&cursor, &lastSynced, &count)
	if err == sql.ErrNoRows {
		return "", time.Time{}, 0, nil
	}
	return
}

// SaveSyncCursor stores the pagination cursor for a resource type.
func (s *Store) SaveSyncCursor(resourceType, cursor string) error {
	s.writeMu.Lock()
	defer s.writeMu.Unlock()
	_, err := s.db.Exec(
		`INSERT INTO sync_state (resource_type, last_cursor, last_synced_at, total_count)
		 VALUES (?, ?, CURRENT_TIMESTAMP, 0)
		 ON CONFLICT(resource_type) DO UPDATE SET last_cursor = ?, last_synced_at = CURRENT_TIMESTAMP`,
		resourceType, cursor, cursor,
	)
	return err
}

// GetSyncCursor returns the last pagination cursor for a resource type.
func (s *Store) GetSyncCursor(resourceType string) string {
	var cursor sql.NullString
	s.db.QueryRow("SELECT last_cursor FROM sync_state WHERE resource_type = ?", resourceType).Scan(&cursor)
	if cursor.Valid {
		return cursor.String
	}
	return ""
}

// ListIDs returns all IDs from a resource's domain table, or from the generic
// resources table if no domain table exists. Used by dependent sync to iterate parents.
func (s *Store) ListIDs(resourceType string) ([]string, error) {
	// Try domain table first (tables are named after the resource type)
	query := fmt.Sprintf("SELECT id FROM %s", resourceType)
	rows, err := s.db.Query(query)
	if err != nil {
		// Fall back to generic resources table
		rows, err = s.db.Query("SELECT id FROM resources WHERE resource_type = ?", resourceType)
		if err != nil {
			return nil, err
		}
	}
	defer rows.Close()

	var ids []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			continue
		}
		ids = append(ids, id)
	}
	return ids, rows.Err()
}

// GetLastSyncedAt returns the last sync timestamp for a resource type.
func (s *Store) GetLastSyncedAt(resourceType string) string {
	var ts sql.NullString
	s.db.QueryRow("SELECT last_synced_at FROM sync_state WHERE resource_type = ?", resourceType).Scan(&ts)
	if ts.Valid {
		return ts.String
	}
	return ""
}

// ClearSyncCursors resets all sync state for a full resync.
func (s *Store) ClearSyncCursors() error {
	s.writeMu.Lock()
	defer s.writeMu.Unlock()
	_, err := s.db.Exec("DELETE FROM sync_state")
	return err
}

// Query executes a raw SQL query and returns the rows.
// Used by workflow commands that need custom queries against the local store.
func (s *Store) Query(query string, args ...any) (*sql.Rows, error) {
	return s.db.Query(query, args...)
}

func (s *Store) Count(resourceType string) (int, error) {
	var count int
	err := s.db.QueryRow(
		`SELECT COUNT(*) FROM resources WHERE resource_type = ?`,
		resourceType,
	).Scan(&count)
	return count, err
}

func (s *Store) Status() (map[string]int, error) {
	rows, err := s.db.Query(
		`SELECT resource_type, COUNT(*) FROM resources GROUP BY resource_type ORDER BY resource_type`,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	status := make(map[string]int)
	for rows.Next() {
		var rt string
		var count int
		if err := rows.Scan(&rt, &count); err != nil {
			return nil, err
		}
		status[rt] = count
	}
	return status, rows.Err()
}

// ResolveByName resolves a human-readable name to a UUID from synced data.
// If the input is already a UUID, it is returned as-is.
// matchFields are JSON field names to search against (e.g., "name", "key", "email").
func (s *Store) ResolveByName(resourceType string, input string, matchFields ...string) (string, error) {
	if IsUUID(input) {
		return input, nil
	}

	var matches []string
	for _, field := range matchFields {
		query := fmt.Sprintf(
			`SELECT id FROM resources WHERE resource_type = ? AND LOWER(json_extract(data, '$.%s')) = LOWER(?)`,
			field,
		)
		rows, err := s.db.Query(query, resourceType, input)
		if err != nil {
			continue
		}
		for rows.Next() {
			var id string
			if rows.Scan(&id) == nil {
				// Deduplicate
				found := false
				for _, m := range matches {
					if m == id {
						found = true
						break
					}
				}
				if !found {
					matches = append(matches, id)
				}
			}
		}
		rows.Close()
	}

	switch len(matches) {
	case 0:
		return "", fmt.Errorf("%s %q not found in local store. Run 'sync' first, or use the UUID directly", resourceType, input)
	case 1:
		return matches[0], nil
	default:
		hint := matches[0]
		if len(matches) > 5 {
			hint = strings.Join(matches[:5], ", ") + "..."
		} else {
			hint = strings.Join(matches, ", ")
		}
		return "", fmt.Errorf("ambiguous: %q matches %d %s entries (%s). Use the exact UUID instead", input, len(matches), resourceType, hint)
	}
}
